/* tslint:disable */
/* eslint-disable */
/**
 * Space Zoo Management API
 * API for managing the Galactic Space Zoo - home to exotic alien creatures from across the universe
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  InspectionCriteriaIn,
  InspectionCriteriaOut,
} from '../models/index';
import {
    InspectionCriteriaInFromJSON,
    InspectionCriteriaInToJSON,
    InspectionCriteriaOutFromJSON,
    InspectionCriteriaOutToJSON,
} from '../models/index';

export interface CriteriaCloneRequest {
    pk: number;
}

export interface CriteriaCreateRequest {
    inspectionCriteriaIn: InspectionCriteriaIn;
}

export interface CriteriaDeleteRequest {
    pk: number;
}

export interface CriteriaGetRequest {
    pk: number;
}

export interface CriteriaListAllRequest {
    id?: string | null;
    text?: string | null;
    audit?: string | null;
    type?: string | null;
    kwargs?: string | null;
    info?: string | null;
    value?: string | null;
    score?: string | null;
    section?: string | null;
    visible?: boolean | null;
}

export interface CriteriaUpdateRequest {
    pk: number;
    inspectionCriteriaIn: InspectionCriteriaIn;
}

/**
 * 
 */
export class AuditFieldsApi extends runtime.BaseAPI {

    /**
     * Duplicate a feeding schedule.
     * Clone
     */
    async criteriaCloneRaw(requestParameters: CriteriaCloneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InspectionCriteriaIn>> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling criteriaClone().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/audit-fields/{pk}/clone`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InspectionCriteriaInFromJSON(jsonValue));
    }

    /**
     * Duplicate a feeding schedule.
     * Clone
     */
    async criteriaClone(requestParameters: CriteriaCloneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InspectionCriteriaIn> {
        const response = await this.criteriaCloneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new feeding schedule.
     * Create
     */
    async criteriaCreateRaw(requestParameters: CriteriaCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InspectionCriteriaOut>> {
        if (requestParameters['inspectionCriteriaIn'] == null) {
            throw new runtime.RequiredError(
                'inspectionCriteriaIn',
                'Required parameter "inspectionCriteriaIn" was null or undefined when calling criteriaCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/audit-fields`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InspectionCriteriaInToJSON(requestParameters['inspectionCriteriaIn']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InspectionCriteriaOutFromJSON(jsonValue));
    }

    /**
     * Create a new feeding schedule.
     * Create
     */
    async criteriaCreate(requestParameters: CriteriaCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InspectionCriteriaOut> {
        const response = await this.criteriaCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove a feeding schedule.
     * Delete
     */
    async criteriaDeleteRaw(requestParameters: CriteriaDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling criteriaDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/audit-fields/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remove a feeding schedule.
     * Delete
     */
    async criteriaDelete(requestParameters: CriteriaDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.criteriaDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Get a feeding record.
     * Get
     */
    async criteriaGetRaw(requestParameters: CriteriaGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InspectionCriteriaOut>> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling criteriaGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/audit-fields/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InspectionCriteriaOutFromJSON(jsonValue));
    }

    /**
     * Get a feeding record.
     * Get
     */
    async criteriaGet(requestParameters: CriteriaGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InspectionCriteriaOut> {
        const response = await this.criteriaGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all feeding schedules.
     * List All
     */
    async criteriaListAllRaw(requestParameters: CriteriaListAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<InspectionCriteriaOut>>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['text'] != null) {
            queryParameters['text'] = requestParameters['text'];
        }

        if (requestParameters['audit'] != null) {
            queryParameters['audit'] = requestParameters['audit'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['kwargs'] != null) {
            queryParameters['kwargs'] = requestParameters['kwargs'];
        }

        if (requestParameters['info'] != null) {
            queryParameters['info'] = requestParameters['info'];
        }

        if (requestParameters['value'] != null) {
            queryParameters['value'] = requestParameters['value'];
        }

        if (requestParameters['score'] != null) {
            queryParameters['score'] = requestParameters['score'];
        }

        if (requestParameters['section'] != null) {
            queryParameters['section'] = requestParameters['section'];
        }

        if (requestParameters['visible'] != null) {
            queryParameters['visible'] = requestParameters['visible'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/audit-fields`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InspectionCriteriaOutFromJSON));
    }

    /**
     * List all feeding schedules.
     * List All
     */
    async criteriaListAll(requestParameters: CriteriaListAllRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InspectionCriteriaOut>> {
        const response = await this.criteriaListAllRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a feeding schedule.
     * Update
     */
    async criteriaUpdateRaw(requestParameters: CriteriaUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InspectionCriteriaOut>> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling criteriaUpdate().'
            );
        }

        if (requestParameters['inspectionCriteriaIn'] == null) {
            throw new runtime.RequiredError(
                'inspectionCriteriaIn',
                'Required parameter "inspectionCriteriaIn" was null or undefined when calling criteriaUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/audit-fields/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: InspectionCriteriaInToJSON(requestParameters['inspectionCriteriaIn']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InspectionCriteriaOutFromJSON(jsonValue));
    }

    /**
     * Update a feeding schedule.
     * Update
     */
    async criteriaUpdate(requestParameters: CriteriaUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InspectionCriteriaOut> {
        const response = await this.criteriaUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
