/* tslint:disable */
/* eslint-disable */
/**
 * Space Zoo Management API
 * API for managing the Galactic Space Zoo - home to exotic alien creatures from across the universe
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SupplyCategoryIn,
  SupplyCategoryNames,
  SupplyCategoryOut,
} from '../models/index';
import {
    SupplyCategoryInFromJSON,
    SupplyCategoryInToJSON,
    SupplyCategoryNamesFromJSON,
    SupplyCategoryNamesToJSON,
    SupplyCategoryOutFromJSON,
    SupplyCategoryOutToJSON,
} from '../models/index';

export interface DependencyTagsApiDeleteRequest {
    pk: number;
}

export interface DependencyTagsApiCloneRequest {
    pk: number;
}

export interface DependencyTagsApiCreateRequest {
    supplyCategoryIn: SupplyCategoryIn;
}

export interface DependencyTagsApiGetRequest {
    pk: number;
}

export interface DependencyTagsApiListAllRequest {
    id?: string | null;
    name?: string | null;
}

export interface DependencyTagsApiListNamesRequest {
    id?: string | null;
    name?: string | null;
}

export interface DependencyTagsApiUpdateRequest {
    pk: number;
    supplyCategoryIn: SupplyCategoryIn;
}

/**
 * 
 */
export class DependencyTagsApi extends runtime.BaseAPI {

    /**
     * Remove a feeding schedule.
     * Delete
     */
    async _deleteRaw(requestParameters: DependencyTagsApiDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling _delete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/dependency-tags/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remove a feeding schedule.
     * Delete
     */
    async _delete(requestParameters: DependencyTagsApiDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this._deleteRaw(requestParameters, initOverrides);
    }

    /**
     * Duplicate a feeding schedule.
     * Clone
     */
    async cloneRaw(requestParameters: DependencyTagsApiCloneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SupplyCategoryOut>> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling clone().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/dependency-tags/{pk}/clone`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SupplyCategoryOutFromJSON(jsonValue));
    }

    /**
     * Duplicate a feeding schedule.
     * Clone
     */
    async clone(requestParameters: DependencyTagsApiCloneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SupplyCategoryOut> {
        const response = await this.cloneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Count all feeding records.
     * Count
     */
    async countRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/dependency-tags/count`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Count all feeding records.
     * Count
     */
    async count(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.countRaw(initOverrides);
        return await response.value();
    }

    /**
     * Create a new feeding schedule.
     * Create
     */
    async createRaw(requestParameters: DependencyTagsApiCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SupplyCategoryOut>> {
        if (requestParameters['supplyCategoryIn'] == null) {
            throw new runtime.RequiredError(
                'supplyCategoryIn',
                'Required parameter "supplyCategoryIn" was null or undefined when calling create().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/dependency-tags`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SupplyCategoryInToJSON(requestParameters['supplyCategoryIn']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SupplyCategoryOutFromJSON(jsonValue));
    }

    /**
     * Create a new feeding schedule.
     * Create
     */
    async create(requestParameters: DependencyTagsApiCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SupplyCategoryOut> {
        const response = await this.createRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a feeding record.
     * Get
     */
    async getRaw(requestParameters: DependencyTagsApiGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SupplyCategoryOut>> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling get().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/dependency-tags/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SupplyCategoryOutFromJSON(jsonValue));
    }

    /**
     * Get a feeding record.
     * Get
     */
    async get(requestParameters: DependencyTagsApiGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SupplyCategoryOut> {
        const response = await this.getRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all feeding schedules.
     * List All
     */
    async listAllRaw(requestParameters: DependencyTagsApiListAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SupplyCategoryOut>>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/dependency-tags`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SupplyCategoryOutFromJSON));
    }

    /**
     * List all feeding schedules.
     * List All
     */
    async listAll(requestParameters: DependencyTagsApiListAllRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SupplyCategoryOut>> {
        const response = await this.listAllRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all names.
     * List Names
     */
    async listNamesRaw(requestParameters: DependencyTagsApiListNamesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SupplyCategoryNames>>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/dependency-tags/names`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SupplyCategoryNamesFromJSON));
    }

    /**
     * List all names.
     * List Names
     */
    async listNames(requestParameters: DependencyTagsApiListNamesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SupplyCategoryNames>> {
        const response = await this.listNamesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a feeding schedule.
     * Update
     */
    async updateRaw(requestParameters: DependencyTagsApiUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SupplyCategoryOut>> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling update().'
            );
        }

        if (requestParameters['supplyCategoryIn'] == null) {
            throw new runtime.RequiredError(
                'supplyCategoryIn',
                'Required parameter "supplyCategoryIn" was null or undefined when calling update().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/dependency-tags/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SupplyCategoryInToJSON(requestParameters['supplyCategoryIn']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SupplyCategoryOutFromJSON(jsonValue));
    }

    /**
     * Update a feeding schedule.
     * Update
     */
    async update(requestParameters: DependencyTagsApiUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SupplyCategoryOut> {
        const response = await this.updateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
