/* tslint:disable */
/* eslint-disable */
/**
 * Space Zoo Management API
 * API for managing the Galactic Space Zoo - home to exotic alien creatures from across the universe
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FoodPackageIn,
  FoodPackageOut,
} from '../models/index';
import {
    FoodPackageInFromJSON,
    FoodPackageInToJSON,
    FoodPackageOutFromJSON,
    FoodPackageOutToJSON,
} from '../models/index';

export interface DeleteRequest {
    pk: number;
}

export interface CloneRequest {
    pk: number;
}

export interface CreateRequest {
    foodPackageIn: FoodPackageIn;
}

export interface GetRequest {
    pk: number;
}

export interface ListAllRequest {
    id?: string | null;
    name?: string | null;
    allowedSpecifier?: string | null;
    latestVersion?: string | null;
    hidden?: boolean | null;
    allowed?: boolean | null;
}

export interface UpdateRequest {
    pk: number;
    foodPackageIn: FoodPackageIn;
}

/**
 * 
 */
export class FoodPackagesApi extends runtime.BaseAPI {

    /**
     * Remove a feeding schedule.
     * Delete
     */
    async _deleteRaw(requestParameters: DeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling _delete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/food-packages/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remove a feeding schedule.
     * Delete
     */
    async _delete(requestParameters: DeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this._deleteRaw(requestParameters, initOverrides);
    }

    /**
     * Duplicate a feeding schedule.
     * Clone
     */
    async cloneRaw(requestParameters: CloneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FoodPackageOut>> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling clone().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/food-packages/{pk}/duplicate`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FoodPackageOutFromJSON(jsonValue));
    }

    /**
     * Duplicate a feeding schedule.
     * Clone
     */
    async clone(requestParameters: CloneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FoodPackageOut> {
        const response = await this.cloneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Count all feeding records.
     * Count
     */
    async countRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/food-packages/count`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Count all feeding records.
     * Count
     */
    async count(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.countRaw(initOverrides);
        return await response.value();
    }

    /**
     * Create a new feeding schedule.
     * Create
     */
    async createRaw(requestParameters: CreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FoodPackageOut>> {
        if (requestParameters['foodPackageIn'] == null) {
            throw new runtime.RequiredError(
                'foodPackageIn',
                'Required parameter "foodPackageIn" was null or undefined when calling create().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/food-packages`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FoodPackageInToJSON(requestParameters['foodPackageIn']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FoodPackageOutFromJSON(jsonValue));
    }

    /**
     * Create a new feeding schedule.
     * Create
     */
    async create(requestParameters: CreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FoodPackageOut> {
        const response = await this.createRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a feeding record.
     * Get
     */
    async getRaw(requestParameters: GetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FoodPackageOut>> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling get().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/food-packages/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FoodPackageOutFromJSON(jsonValue));
    }

    /**
     * Get a feeding record.
     * Get
     */
    async get(requestParameters: GetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FoodPackageOut> {
        const response = await this.getRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all feeding schedules.
     * List All
     */
    async listAllRaw(requestParameters: ListAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<FoodPackageOut>>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['allowedSpecifier'] != null) {
            queryParameters['allowedSpecifier'] = requestParameters['allowedSpecifier'];
        }

        if (requestParameters['latestVersion'] != null) {
            queryParameters['latestVersion'] = requestParameters['latestVersion'];
        }

        if (requestParameters['hidden'] != null) {
            queryParameters['hidden'] = requestParameters['hidden'];
        }

        if (requestParameters['allowed'] != null) {
            queryParameters['allowed'] = requestParameters['allowed'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/food-packages`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FoodPackageOutFromJSON));
    }

    /**
     * List all feeding schedules.
     * List All
     */
    async listAll(requestParameters: ListAllRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<FoodPackageOut>> {
        const response = await this.listAllRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a feeding schedule.
     * Update
     */
    async updateRaw(requestParameters: UpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FoodPackageOut>> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling update().'
            );
        }

        if (requestParameters['foodPackageIn'] == null) {
            throw new runtime.RequiredError(
                'foodPackageIn',
                'Required parameter "foodPackageIn" was null or undefined when calling update().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/food-packages/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: FoodPackageInToJSON(requestParameters['foodPackageIn']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FoodPackageOutFromJSON(jsonValue));
    }

    /**
     * Update a feeding schedule.
     * Update
     */
    async update(requestParameters: UpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FoodPackageOut> {
        const response = await this.updateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
