/* tslint:disable */
/* eslint-disable */
/**
 * Space Zoo Management API
 * API for managing the Galactic Space Zoo - home to exotic alien creatures from across the universe
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MigrationMetricIn,
  MigrationMetricOut,
} from '../models/index';
import {
    MigrationMetricInFromJSON,
    MigrationMetricInToJSON,
    MigrationMetricOutFromJSON,
    MigrationMetricOutToJSON,
} from '../models/index';

export interface GitLabMetricsApiDeleteRequest {
    pk: number;
}

export interface GitLabMetricsApiCloneRequest {
    pk: number;
}

export interface GitLabMetricsApiCreateRequest {
    migrationMetricIn: MigrationMetricIn;
}

export interface GitLabMetricsApiGetRequest {
    pk: number;
}

export interface GitLabMetricsApiListAllRequest {
    id?: string | null;
    metricId?: string | null;
    datetime?: string | null;
    habitat?: string | null;
    lastCommit?: string | null;
    commits?: string | null;
    lastRelease?: string | null;
    openIssues?: string | null;
    closedIssues?: string | null;
    featureIssues?: string | null;
    closedFeatureIssues?: string | null;
    bugIssues?: string | null;
    closedBugIssues?: string | null;
    bugTtl?: string | null;
    doingTime?: string | null;
    reviewTime?: string | null;
    codeQuality?: string | null;
}

export interface GitLabMetricsApiUpdateRequest {
    pk: number;
    migrationMetricIn: MigrationMetricIn;
}

/**
 * 
 */
export class GitLabMetricsApi extends runtime.BaseAPI {

    /**
     * Remove a feeding schedule.
     * Delete
     */
    async _deleteRaw(requestParameters: GitLabMetricsApiDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling _delete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/gitlab-metrics/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remove a feeding schedule.
     * Delete
     */
    async _delete(requestParameters: GitLabMetricsApiDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this._deleteRaw(requestParameters, initOverrides);
    }

    /**
     * Duplicate a feeding schedule.
     * Clone
     */
    async cloneRaw(requestParameters: GitLabMetricsApiCloneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MigrationMetricOut>> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling clone().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/gitlab-metrics/{pk}/clone`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MigrationMetricOutFromJSON(jsonValue));
    }

    /**
     * Duplicate a feeding schedule.
     * Clone
     */
    async clone(requestParameters: GitLabMetricsApiCloneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MigrationMetricOut> {
        const response = await this.cloneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Count all feeding records.
     * Count
     */
    async countRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/gitlab-metrics/count`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Count all feeding records.
     * Count
     */
    async count(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.countRaw(initOverrides);
        return await response.value();
    }

    /**
     * Create a new feeding schedule.
     * Create
     */
    async createRaw(requestParameters: GitLabMetricsApiCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MigrationMetricOut>> {
        if (requestParameters['migrationMetricIn'] == null) {
            throw new runtime.RequiredError(
                'migrationMetricIn',
                'Required parameter "migrationMetricIn" was null or undefined when calling create().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/gitlab-metrics`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MigrationMetricInToJSON(requestParameters['migrationMetricIn']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MigrationMetricOutFromJSON(jsonValue));
    }

    /**
     * Create a new feeding schedule.
     * Create
     */
    async create(requestParameters: GitLabMetricsApiCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MigrationMetricOut> {
        const response = await this.createRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a feeding record.
     * Get
     */
    async getRaw(requestParameters: GitLabMetricsApiGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MigrationMetricOut>> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling get().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/gitlab-metrics/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MigrationMetricOutFromJSON(jsonValue));
    }

    /**
     * Get a feeding record.
     * Get
     */
    async get(requestParameters: GitLabMetricsApiGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MigrationMetricOut> {
        const response = await this.getRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all feeding schedules.
     * List All
     */
    async listAllRaw(requestParameters: GitLabMetricsApiListAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MigrationMetricOut>>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['metricId'] != null) {
            queryParameters['metricId'] = requestParameters['metricId'];
        }

        if (requestParameters['datetime'] != null) {
            queryParameters['datetime'] = requestParameters['datetime'];
        }

        if (requestParameters['habitat'] != null) {
            queryParameters['habitat'] = requestParameters['habitat'];
        }

        if (requestParameters['lastCommit'] != null) {
            queryParameters['lastCommit'] = requestParameters['lastCommit'];
        }

        if (requestParameters['commits'] != null) {
            queryParameters['commits'] = requestParameters['commits'];
        }

        if (requestParameters['lastRelease'] != null) {
            queryParameters['lastRelease'] = requestParameters['lastRelease'];
        }

        if (requestParameters['openIssues'] != null) {
            queryParameters['openIssues'] = requestParameters['openIssues'];
        }

        if (requestParameters['closedIssues'] != null) {
            queryParameters['closedIssues'] = requestParameters['closedIssues'];
        }

        if (requestParameters['featureIssues'] != null) {
            queryParameters['featureIssues'] = requestParameters['featureIssues'];
        }

        if (requestParameters['closedFeatureIssues'] != null) {
            queryParameters['closedFeatureIssues'] = requestParameters['closedFeatureIssues'];
        }

        if (requestParameters['bugIssues'] != null) {
            queryParameters['bugIssues'] = requestParameters['bugIssues'];
        }

        if (requestParameters['closedBugIssues'] != null) {
            queryParameters['closedBugIssues'] = requestParameters['closedBugIssues'];
        }

        if (requestParameters['bugTtl'] != null) {
            queryParameters['bugTtl'] = requestParameters['bugTtl'];
        }

        if (requestParameters['doingTime'] != null) {
            queryParameters['doingTime'] = requestParameters['doingTime'];
        }

        if (requestParameters['reviewTime'] != null) {
            queryParameters['reviewTime'] = requestParameters['reviewTime'];
        }

        if (requestParameters['codeQuality'] != null) {
            queryParameters['codeQuality'] = requestParameters['codeQuality'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/gitlab-metrics`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MigrationMetricOutFromJSON));
    }

    /**
     * List all feeding schedules.
     * List All
     */
    async listAll(requestParameters: GitLabMetricsApiListAllRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MigrationMetricOut>> {
        const response = await this.listAllRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a feeding schedule.
     * Update
     */
    async updateRaw(requestParameters: GitLabMetricsApiUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MigrationMetricOut>> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling update().'
            );
        }

        if (requestParameters['migrationMetricIn'] == null) {
            throw new runtime.RequiredError(
                'migrationMetricIn',
                'Required parameter "migrationMetricIn" was null or undefined when calling update().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/gitlab-metrics/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: MigrationMetricInToJSON(requestParameters['migrationMetricIn']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MigrationMetricOutFromJSON(jsonValue));
    }

    /**
     * Update a feeding schedule.
     * Update
     */
    async update(requestParameters: GitLabMetricsApiUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MigrationMetricOut> {
        const response = await this.updateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
