/* tslint:disable */
/* eslint-disable */
/**
 * Space Zoo Management API
 * API for managing the Galactic Space Zoo - home to exotic alien creatures from across the universe
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by openapi-ts-client.
 * https://github.com/fa-krug/openapi-ts-client
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FeedingOut,
  InspectionChange,
  InspectionCriteriaIn,
  InspectionCriteriaOut,
  InspectionIn,
  InspectionIssue,
  InspectionNames,
  InspectionOut,
  ResultSchema,
} from '../models/index';
import {
    FeedingOutFromJSON,
    FeedingOutToJSON,
    InspectionChangeFromJSON,
    InspectionChangeToJSON,
    InspectionCriteriaInFromJSON,
    InspectionCriteriaInToJSON,
    InspectionCriteriaOutFromJSON,
    InspectionCriteriaOutToJSON,
    InspectionInFromJSON,
    InspectionInToJSON,
    InspectionIssueFromJSON,
    InspectionIssueToJSON,
    InspectionNamesFromJSON,
    InspectionNamesToJSON,
    InspectionOutFromJSON,
    InspectionOutToJSON,
    ResultSchemaFromJSON,
    ResultSchemaToJSON,
} from '../models/index';

export interface InspectionsApiDeleteRequest {
    pk: number;
}

export interface InspectionsApiCloneRequest {
    pk: number;
}

export interface InspectionsApiCreateRequest {
    inspectionIn: InspectionIn;
}

export interface InspectionsApiGetRequest {
    pk: number;
}

export interface InspectionsApiGetAuditChartRequest {
    pk: number;
    simplify?: boolean;
}

export interface InspectionsApiGetAuditScoresRequest {
    pk: number;
    simplify?: boolean;
}

export interface InspectionsApiListAllRequest {
    id?: string | null;
    name?: string | null;
    template?: string | null;
    habitat?: string | null;
    lastAudit?: string | null;
    content?: string | null;
    version?: string | null;
    status?: string | null;
    score?: string | null;
    archived?: boolean | null;
    start?: string | null;
    end?: string | null;
    summary?: string | null;
}

export interface InspectionsApiListAuditActionsRequest {
    pk: number;
    id?: string | null;
    value?: string | null;
    keeper?: string | null;
    creature?: string | null;
    priority?: string | null;
    start?: string | null;
    end?: string | null;
    habitat?: string | null;
    administered?: boolean | null;
    feedingDate?: string | null;
}

export interface InspectionsApiListAuditChangesRequest {
    pk: number;
}

export interface InspectionsApiListAuditFieldsRequest {
    pk: number;
}

export interface InspectionsApiListAuditProblemsRequest {
    pk: number;
}

export interface InspectionsApiListNamesRequest {
    id?: string | null;
    name?: string | null;
    template?: string | null;
    habitat?: string | null;
    lastAudit?: string | null;
    content?: string | null;
    version?: string | null;
    status?: string | null;
    score?: string | null;
    archived?: boolean | null;
    start?: string | null;
    end?: string | null;
    summary?: string | null;
}

export interface InspectionsApiUpdateRequest {
    pk: number;
    inspectionIn: InspectionIn;
}

export interface InspectionsApiUpdateAuditFieldsRequest {
    pk: number;
    inspectionCriteriaIn: Array<InspectionCriteriaIn>;
}

/**
 * 
 */
export class InspectionsApi extends runtime.BaseAPI {

    /**
     * Remove a feeding schedule.
     * Delete
     */
    async _deleteRaw(requestParameters: InspectionsApiDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling _delete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/inspections/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remove a feeding schedule.
     * Delete
     */
    async _delete(requestParameters: InspectionsApiDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this._deleteRaw(requestParameters, initOverrides);
    }

    /**
     * Duplicate a feeding schedule.
     * Clone
     */
    async cloneRaw(requestParameters: InspectionsApiCloneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InspectionOut>> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling clone().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/inspections/{pk}/duplicate`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InspectionOutFromJSON(jsonValue));
    }

    /**
     * Duplicate a feeding schedule.
     * Clone
     */
    async clone(requestParameters: InspectionsApiCloneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InspectionOut> {
        const response = await this.cloneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Count all active entries.
     * Count Active
     */
    async countActiveRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/audits/count-active`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Count all active entries.
     * Count Active
     */
    async countActive(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.countActiveRaw(initOverrides);
        return await response.value();
    }

    /**
     * Count all archived entries.
     * Count Archived
     */
    async countArchivedRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/audits/count-archived`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Count all archived entries.
     * Count Archived
     */
    async countArchived(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.countArchivedRaw(initOverrides);
        return await response.value();
    }

    /**
     * Create a new feeding schedule.
     * Create
     */
    async createRaw(requestParameters: InspectionsApiCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InspectionOut>> {
        if (requestParameters['inspectionIn'] == null) {
            throw new runtime.RequiredError(
                'inspectionIn',
                'Required parameter "inspectionIn" was null or undefined when calling create().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/inspections`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InspectionInToJSON(requestParameters['inspectionIn']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InspectionOutFromJSON(jsonValue));
    }

    /**
     * Create a new feeding schedule.
     * Create
     */
    async create(requestParameters: InspectionsApiCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InspectionOut> {
        const response = await this.createRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a feeding record.
     * Get
     */
    async getRaw(requestParameters: InspectionsApiGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InspectionOut>> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling get().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/inspections/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InspectionOutFromJSON(jsonValue));
    }

    /**
     * Get a feeding record.
     * Get
     */
    async get(requestParameters: InspectionsApiGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InspectionOut> {
        const response = await this.getRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get graph data for an audit.
     * Get Audit Chart
     */
    async getAuditChartRaw(requestParameters: InspectionsApiGetAuditChartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultSchema>> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling getAuditChart().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['simplify'] != null) {
            queryParameters['simplify'] = requestParameters['simplify'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/audits/{pk}/chart`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultSchemaFromJSON(jsonValue));
    }

    /**
     * Get graph data for an audit.
     * Get Audit Chart
     */
    async getAuditChart(requestParameters: InspectionsApiGetAuditChartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultSchema> {
        const response = await this.getAuditChartRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get score data for an audit.
     * Get Audit Scores
     */
    async getAuditScoresRaw(requestParameters: InspectionsApiGetAuditScoresRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: number; }>> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling getAuditScores().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['simplify'] != null) {
            queryParameters['simplify'] = requestParameters['simplify'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/audits/{pk}/scores`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get score data for an audit.
     * Get Audit Scores
     */
    async getAuditScores(requestParameters: InspectionsApiGetAuditScoresRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: number; }> {
        const response = await this.getAuditScoresRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all feeding schedules.
     * List All
     */
    async listAllRaw(requestParameters: InspectionsApiListAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<InspectionOut>>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['template'] != null) {
            queryParameters['template'] = requestParameters['template'];
        }

        if (requestParameters['habitat'] != null) {
            queryParameters['habitat'] = requestParameters['habitat'];
        }

        if (requestParameters['lastAudit'] != null) {
            queryParameters['lastAudit'] = requestParameters['lastAudit'];
        }

        if (requestParameters['content'] != null) {
            queryParameters['content'] = requestParameters['content'];
        }

        if (requestParameters['version'] != null) {
            queryParameters['version'] = requestParameters['version'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['score'] != null) {
            queryParameters['score'] = requestParameters['score'];
        }

        if (requestParameters['archived'] != null) {
            queryParameters['archived'] = requestParameters['archived'];
        }

        if (requestParameters['start'] != null) {
            queryParameters['start'] = requestParameters['start'];
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = requestParameters['end'];
        }

        if (requestParameters['summary'] != null) {
            queryParameters['summary'] = requestParameters['summary'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/inspections`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InspectionOutFromJSON));
    }

    /**
     * List all feeding schedules.
     * List All
     */
    async listAll(requestParameters: InspectionsApiListAllRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InspectionOut>> {
        const response = await this.listAllRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all actions for an audit.
     * List Audit Actions
     */
    async listAuditActionsRaw(requestParameters: InspectionsApiListAuditActionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<FeedingOut>>> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling listAuditActions().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['value'] != null) {
            queryParameters['value'] = requestParameters['value'];
        }

        if (requestParameters['keeper'] != null) {
            queryParameters['keeper'] = requestParameters['keeper'];
        }

        if (requestParameters['creature'] != null) {
            queryParameters['creature'] = requestParameters['creature'];
        }

        if (requestParameters['priority'] != null) {
            queryParameters['priority'] = requestParameters['priority'];
        }

        if (requestParameters['start'] != null) {
            queryParameters['start'] = requestParameters['start'];
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = requestParameters['end'];
        }

        if (requestParameters['habitat'] != null) {
            queryParameters['habitat'] = requestParameters['habitat'];
        }

        if (requestParameters['administered'] != null) {
            queryParameters['administered'] = requestParameters['administered'];
        }

        if (requestParameters['feedingDate'] != null) {
            queryParameters['feedingDate'] = requestParameters['feedingDate'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/audits/{pk}/actions`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FeedingOutFromJSON));
    }

    /**
     * List all actions for an audit.
     * List Audit Actions
     */
    async listAuditActions(requestParameters: InspectionsApiListAuditActionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<FeedingOut>> {
        const response = await this.listAuditActionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all changes for an audit.
     * List Audit Changes
     */
    async listAuditChangesRaw(requestParameters: InspectionsApiListAuditChangesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<InspectionChange>>> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling listAuditChanges().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/inspections/{pk}/changes`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InspectionChangeFromJSON));
    }

    /**
     * List all changes for an audit.
     * List Audit Changes
     */
    async listAuditChanges(requestParameters: InspectionsApiListAuditChangesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InspectionChange>> {
        const response = await this.listAuditChangesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all fields for an audit.
     * List Audit Fields
     */
    async listAuditFieldsRaw(requestParameters: InspectionsApiListAuditFieldsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<InspectionCriteriaOut>>> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling listAuditFields().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/audits/{pk}/fields`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InspectionCriteriaOutFromJSON));
    }

    /**
     * List all fields for an audit.
     * List Audit Fields
     */
    async listAuditFields(requestParameters: InspectionsApiListAuditFieldsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InspectionCriteriaOut>> {
        const response = await this.listAuditFieldsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all problems for an audit.
     * List Audit Problems
     */
    async listAuditProblemsRaw(requestParameters: InspectionsApiListAuditProblemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<InspectionIssue>>> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling listAuditProblems().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/inspections/{pk}/issues`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InspectionIssueFromJSON));
    }

    /**
     * List all problems for an audit.
     * List Audit Problems
     */
    async listAuditProblems(requestParameters: InspectionsApiListAuditProblemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InspectionIssue>> {
        const response = await this.listAuditProblemsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all names.
     * List Names
     */
    async listNamesRaw(requestParameters: InspectionsApiListNamesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<InspectionNames>>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['template'] != null) {
            queryParameters['template'] = requestParameters['template'];
        }

        if (requestParameters['habitat'] != null) {
            queryParameters['habitat'] = requestParameters['habitat'];
        }

        if (requestParameters['lastAudit'] != null) {
            queryParameters['lastAudit'] = requestParameters['lastAudit'];
        }

        if (requestParameters['content'] != null) {
            queryParameters['content'] = requestParameters['content'];
        }

        if (requestParameters['version'] != null) {
            queryParameters['version'] = requestParameters['version'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['score'] != null) {
            queryParameters['score'] = requestParameters['score'];
        }

        if (requestParameters['archived'] != null) {
            queryParameters['archived'] = requestParameters['archived'];
        }

        if (requestParameters['start'] != null) {
            queryParameters['start'] = requestParameters['start'];
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = requestParameters['end'];
        }

        if (requestParameters['summary'] != null) {
            queryParameters['summary'] = requestParameters['summary'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/audits/names`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InspectionNamesFromJSON));
    }

    /**
     * List all names.
     * List Names
     */
    async listNames(requestParameters: InspectionsApiListNamesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InspectionNames>> {
        const response = await this.listNamesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a feeding schedule.
     * Update
     */
    async updateRaw(requestParameters: InspectionsApiUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InspectionOut>> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling update().'
            );
        }

        if (requestParameters['inspectionIn'] == null) {
            throw new runtime.RequiredError(
                'inspectionIn',
                'Required parameter "inspectionIn" was null or undefined when calling update().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/inspections/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: InspectionInToJSON(requestParameters['inspectionIn']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InspectionOutFromJSON(jsonValue));
    }

    /**
     * Update a feeding schedule.
     * Update
     */
    async update(requestParameters: InspectionsApiUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InspectionOut> {
        const response = await this.updateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update fields for an audit.
     * Update Audit Fields
     */
    async updateAuditFieldsRaw(requestParameters: InspectionsApiUpdateAuditFieldsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<InspectionCriteriaOut>>> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling updateAuditFields().'
            );
        }

        if (requestParameters['inspectionCriteriaIn'] == null) {
            throw new runtime.RequiredError(
                'inspectionCriteriaIn',
                'Required parameter "inspectionCriteriaIn" was null or undefined when calling updateAuditFields().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/audits/{pk}/fields`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['inspectionCriteriaIn']!.map(InspectionCriteriaInToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InspectionCriteriaOutFromJSON));
    }

    /**
     * Update fields for an audit.
     * Update Audit Fields
     */
    async updateAuditFields(requestParameters: InspectionsApiUpdateAuditFieldsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InspectionCriteriaOut>> {
        const response = await this.updateAuditFieldsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
