/* tslint:disable */
/* eslint-disable */
/**
 * Space Zoo Management API
 * API for managing the Galactic Space Zoo - home to exotic alien creatures from across the universe
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ActivityLogSchema,
  ResultSchema,
} from '../models/index';
import {
    ActivityLogSchemaFromJSON,
    ActivityLogSchemaToJSON,
    ResultSchemaFromJSON,
    ResultSchemaToJSON,
} from '../models/index';

export interface OtlpTracesRequest {
    activityLogSchema: ActivityLogSchema;
}

/**
 * 
 */
export class OTLPApi extends runtime.BaseAPI {

    /**
     * Receive and process OpenTelemetry protocol (OTLP) trace requests.
     * Otlp Traces
     */
    async otlpTracesRaw(requestParameters: OtlpTracesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultSchema>> {
        if (requestParameters['activityLogSchema'] == null) {
            throw new runtime.RequiredError(
                'activityLogSchema',
                'Required parameter "activityLogSchema" was null or undefined when calling otlpTraces().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/otlp/otlp/v1/traces/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ActivityLogSchemaToJSON(requestParameters['activityLogSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultSchemaFromJSON(jsonValue));
    }

    /**
     * Receive and process OpenTelemetry protocol (OTLP) trace requests.
     * Otlp Traces
     */
    async otlpTraces(requestParameters: OtlpTracesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultSchema> {
        const response = await this.otlpTracesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
