/* tslint:disable */
/* eslint-disable */
/**
 * Space Zoo Management API
 * API for managing the Galactic Space Zoo - home to exotic alien creatures from across the universe
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by openapi-ts-client.
 * https://github.com/fa-krug/openapi-ts-client
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PermitIn,
  PermitOut,
} from '../models/index';
import {
    PermitInFromJSON,
    PermitInToJSON,
    PermitOutFromJSON,
    PermitOutToJSON,
} from '../models/index';

export interface PermitsApiDeleteRequest {
    pk: number;
}

export interface PermitsApiCloneRequest {
    pk: number;
}

export interface PermitsApiCreateRequest {
    permitIn: PermitIn;
}

export interface PermitsApiGetRequest {
    pk: number;
}

export interface PermitsApiListAllRequest {
    id?: string | null;
    name?: string | null;
    allowed?: boolean | null;
    riskScore?: string | null;
    sourceUrl?: string | null;
}

export interface PermitsApiUpdateRequest {
    pk: number;
    permitIn: PermitIn;
}

/**
 * 
 */
export class PermitsApi extends runtime.BaseAPI {

    /**
     * Remove a feeding schedule.
     * Delete
     */
    async _deleteRaw(requestParameters: PermitsApiDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling _delete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/permits/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remove a feeding schedule.
     * Delete
     */
    async _delete(requestParameters: PermitsApiDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this._deleteRaw(requestParameters, initOverrides);
    }

    /**
     * Duplicate a feeding schedule.
     * Clone
     */
    async cloneRaw(requestParameters: PermitsApiCloneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PermitOut>> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling clone().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/permits/{pk}/duplicate`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PermitOutFromJSON(jsonValue));
    }

    /**
     * Duplicate a feeding schedule.
     * Clone
     */
    async clone(requestParameters: PermitsApiCloneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PermitOut> {
        const response = await this.cloneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Count all feeding records.
     * Count
     */
    async countRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/permits/count`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Count all feeding records.
     * Count
     */
    async count(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.countRaw(initOverrides);
        return await response.value();
    }

    /**
     * Create a new feeding schedule.
     * Create
     */
    async createRaw(requestParameters: PermitsApiCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PermitOut>> {
        if (requestParameters['permitIn'] == null) {
            throw new runtime.RequiredError(
                'permitIn',
                'Required parameter "permitIn" was null or undefined when calling create().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/permits`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PermitInToJSON(requestParameters['permitIn']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PermitOutFromJSON(jsonValue));
    }

    /**
     * Create a new feeding schedule.
     * Create
     */
    async create(requestParameters: PermitsApiCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PermitOut> {
        const response = await this.createRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a feeding record.
     * Get
     */
    async getRaw(requestParameters: PermitsApiGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PermitOut>> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling get().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/permits/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PermitOutFromJSON(jsonValue));
    }

    /**
     * Get a feeding record.
     * Get
     */
    async get(requestParameters: PermitsApiGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PermitOut> {
        const response = await this.getRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all feeding schedules.
     * List All
     */
    async listAllRaw(requestParameters: PermitsApiListAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PermitOut>>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['allowed'] != null) {
            queryParameters['allowed'] = requestParameters['allowed'];
        }

        if (requestParameters['riskScore'] != null) {
            queryParameters['riskScore'] = requestParameters['riskScore'];
        }

        if (requestParameters['sourceUrl'] != null) {
            queryParameters['sourceUrl'] = requestParameters['sourceUrl'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/permits`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PermitOutFromJSON));
    }

    /**
     * List all feeding schedules.
     * List All
     */
    async listAll(requestParameters: PermitsApiListAllRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PermitOut>> {
        const response = await this.listAllRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a feeding schedule.
     * Update
     */
    async updateRaw(requestParameters: PermitsApiUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PermitOut>> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling update().'
            );
        }

        if (requestParameters['permitIn'] == null) {
            throw new runtime.RequiredError(
                'permitIn',
                'Required parameter "permitIn" was null or undefined when calling update().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/permits/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PermitInToJSON(requestParameters['permitIn']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PermitOutFromJSON(jsonValue));
    }

    /**
     * Update a feeding schedule.
     * Update
     */
    async update(requestParameters: PermitsApiUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PermitOut> {
        const response = await this.updateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
