/* tslint:disable */
/* eslint-disable */
/**
 * Space Zoo Management API
 * API for managing the Galactic Space Zoo - home to exotic alien creatures from across the universe
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BiomeTypeIn,
  BiomeTypeOut,
} from '../models/index';
import {
    BiomeTypeInFromJSON,
    BiomeTypeInToJSON,
    BiomeTypeOutFromJSON,
    BiomeTypeOutToJSON,
} from '../models/index';

export interface SonarQubeProjectsApiDeleteRequest {
    pk: number;
}

export interface SonarQubeProjectsApiCloneRequest {
    pk: number;
}

export interface SonarQubeProjectsApiCreateRequest {
    biomeTypeIn: BiomeTypeIn;
}

export interface SonarQubeProjectsApiGetRequest {
    pk: number;
}

export interface SonarQubeProjectsApiListAllRequest {
    id?: string | null;
    biomeCode?: string | null;
    name?: string | null;
    habitat?: string | null;
}

export interface SonarQubeProjectsApiUpdateRequest {
    pk: number;
    biomeTypeIn: BiomeTypeIn;
}

/**
 * 
 */
export class SonarQubeProjectsApi extends runtime.BaseAPI {

    /**
     * Remove a feeding schedule.
     * Delete
     */
    async _deleteRaw(requestParameters: SonarQubeProjectsApiDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling _delete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/sonarqube-projects/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remove a feeding schedule.
     * Delete
     */
    async _delete(requestParameters: SonarQubeProjectsApiDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this._deleteRaw(requestParameters, initOverrides);
    }

    /**
     * Duplicate a feeding schedule.
     * Clone
     */
    async cloneRaw(requestParameters: SonarQubeProjectsApiCloneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BiomeTypeOut>> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling clone().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/sonarqube-projects/{pk}/clone`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BiomeTypeOutFromJSON(jsonValue));
    }

    /**
     * Duplicate a feeding schedule.
     * Clone
     */
    async clone(requestParameters: SonarQubeProjectsApiCloneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BiomeTypeOut> {
        const response = await this.cloneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new feeding schedule.
     * Create
     */
    async createRaw(requestParameters: SonarQubeProjectsApiCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BiomeTypeOut>> {
        if (requestParameters['biomeTypeIn'] == null) {
            throw new runtime.RequiredError(
                'biomeTypeIn',
                'Required parameter "biomeTypeIn" was null or undefined when calling create().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/sonarqube-projects`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BiomeTypeInToJSON(requestParameters['biomeTypeIn']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BiomeTypeOutFromJSON(jsonValue));
    }

    /**
     * Create a new feeding schedule.
     * Create
     */
    async create(requestParameters: SonarQubeProjectsApiCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BiomeTypeOut> {
        const response = await this.createRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a feeding record.
     * Get
     */
    async getRaw(requestParameters: SonarQubeProjectsApiGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BiomeTypeOut>> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling get().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/sonarqube-projects/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BiomeTypeOutFromJSON(jsonValue));
    }

    /**
     * Get a feeding record.
     * Get
     */
    async get(requestParameters: SonarQubeProjectsApiGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BiomeTypeOut> {
        const response = await this.getRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all feeding schedules.
     * List All
     */
    async listAllRaw(requestParameters: SonarQubeProjectsApiListAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BiomeTypeOut>>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['biomeCode'] != null) {
            queryParameters['biomeCode'] = requestParameters['biomeCode'];
        }

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['habitat'] != null) {
            queryParameters['habitat'] = requestParameters['habitat'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/sonarqube-projects`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BiomeTypeOutFromJSON));
    }

    /**
     * List all feeding schedules.
     * List All
     */
    async listAll(requestParameters: SonarQubeProjectsApiListAllRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BiomeTypeOut>> {
        const response = await this.listAllRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a feeding schedule.
     * Update
     */
    async updateRaw(requestParameters: SonarQubeProjectsApiUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BiomeTypeOut>> {
        if (requestParameters['pk'] == null) {
            throw new runtime.RequiredError(
                'pk',
                'Required parameter "pk" was null or undefined when calling update().'
            );
        }

        if (requestParameters['biomeTypeIn'] == null) {
            throw new runtime.RequiredError(
                'biomeTypeIn',
                'Required parameter "biomeTypeIn" was null or undefined when calling update().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/sonarqube-projects/{pk}`;
        urlPath = urlPath.replace(`{${"pk"}}`, encodeURIComponent(String(requestParameters['pk'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: BiomeTypeInToJSON(requestParameters['biomeTypeIn']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BiomeTypeOutFromJSON(jsonValue));
    }

    /**
     * Update a feeding schedule.
     * Update
     */
    async update(requestParameters: SonarQubeProjectsApiUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BiomeTypeOut> {
        const response = await this.updateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
