/**
 * Tic Tac Toe
 *
 * 
 *
 * NOTE: This file is auto generated by openapi-ts-client.
 * https://github.com/fa-krug/openapi-ts-client
 * Do not edit the class manually.
 */


/**
 * Winner of the game. `.` means nobody has won yet.
 */
export const Winner = {
    Period: '.',
    X: 'X',
    O: 'O'
} as const;
export type Winner = typeof Winner[keyof typeof Winner];

