/**
 * Space Zoo Management API
 *
 * 
 *
 * NOTE: This file is auto generated by openapi-ts-client.
 * https://github.com/fa-krug/openapi-ts-client
 * Do not edit the class manually.
 */


/**
 * Schema for OTLP traces.
 */
export interface ActivityLogSchema { 
    resourceSpans: Array<any>;
}

