/**
 * Space Zoo Management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BehaviorMetricFilter { 
    id?: string | null;
    spanId?: string | null;
    start?: string | null;
    end?: string | null;
    timespanNs?: string | null;
    httpMetric?: string | null;
    name?: string | null;
    value?: string | null;
    details?: string | null;
    createdBy?: string | null;
    message?: string | null;
    state?: string | null;
}

