/**
 * Space Zoo Management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BehaviorMetricOut { 
    id?: number | null;
    spanId?: string | null;
    start?: string | null;
    end?: string | null;
    timespanNs?: number | null;
    http_metric_id?: number | null;
    name?: string | null;
    value?: number | null;
    details?: object | null;
    createdBy?: string | null;
    message?: string | null;
    state?: string | null;
}

