/**
 * Space Zoo Management API
 *
 * 
 *
 * NOTE: This file is auto generated by openapi-ts-client.
 * https://github.com/fa-krug/openapi-ts-client
 * Do not edit the class manually.
 */


export interface BiomeTypeFilter { 
    id?: string | null;
    biomeCode?: string | null;
    name?: string | null;
    habitat?: string | null;
}

