/**
 * Space Zoo Management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BiomeTypeFilter { 
    id?: string | null;
    biomeCode?: string | null;
    name?: string | null;
    habitat?: string | null;
}

