/**
 * Space Zoo Management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EnclosureOut { 
    id?: number | null;
    name: string;
    timestamp: string;
    habitat_id?: number | null;
}

