/**
 * Space Zoo Management API
 *
 * 
 *
 * NOTE: This file is auto generated by openapi-ts-client.
 * https://github.com/fa-krug/openapi-ts-client
 * Do not edit the class manually.
 */


export interface FeedingIn { 
    id?: number | null;
    value?: string | null;
    keeper?: string | null;
    creature?: string | null;
    priority?: string | null;
    start?: string | null;
    end?: string | null;
    habitat_id?: number | null;
    administered?: boolean | null;
    feedingDate?: string | null;
}

