/**
 * Space Zoo Management API
 *
 * 
 *
 * NOTE: This file is auto generated by openapi-ts-client.
 * https://github.com/fa-krug/openapi-ts-client
 * Do not edit the class manually.
 */


export interface FoodPackageOut { 
    id?: number | null;
    name: string;
    allowedSpecifier?: string | null;
    latestVersion?: string | null;
    hidden?: boolean;
    allowed?: boolean | null;
}

