/**
 * Space Zoo Management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BiomeTypeIn } from './biomeTypeIn';
import { EnclosureIn } from './enclosureIn';
import { OriginPlanetIn } from './originPlanetIn';


export interface HabitatOut { 
    originPlanets: Array<OriginPlanetIn>;
    biomeTypes: Array<BiomeTypeIn>;
    enclosures: Array<EnclosureIn>;
    id?: number | null;
    name: string;
}

