/**
 * Space Zoo Management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HealthReportIn { 
    id?: number | null;
    name?: string | null;
    latestAudits?: boolean | null;
    startDate?: string | null;
    endDate?: string | null;
    type?: string | null;
    simplify?: boolean | null;
    blocks?: string | null;
    permission?: string | null;
    privacy?: string | null;
    audit?: Array<number> | null;
    template?: Array<number> | null;
}

