/**
 * Space Zoo Management API
 *
 * 
 *
 * NOTE: This file is auto generated by openapi-ts-client.
 * https://github.com/fa-krug/openapi-ts-client
 * Do not edit the class manually.
 */


export interface HealthReportOut { 
    id?: number | null;
    name: string;
    latestAudits?: boolean;
    startDate?: string | null;
    endDate?: string | null;
    type?: string;
    simplify?: boolean;
    blocks?: string | null;
    permission?: string;
    privacy?: string;
    audit: Array<number>;
    template: Array<number>;
}

