/**
 * Space Zoo Management API
 *
 * 
 *
 * NOTE: This file is auto generated by openapi-ts-client.
 * https://github.com/fa-krug/openapi-ts-client
 * Do not edit the class manually.
 */


export interface InspectionCriteriaFilter { 
    id?: string | null;
    text?: string | null;
    audit?: string | null;
    type?: string | null;
    kwargs?: string | null;
    info?: string | null;
    value?: string | null;
    score?: string | null;
    section?: string | null;
    visible?: boolean | null;
}

