/**
 * Space Zoo Management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Score } from './score';


export interface InspectionCriteriaOut { 
    last: string | null;
    id?: number | null;
    text: string;
    audit_id: number;
    type: string;
    kwargs?: object | null;
    info?: string | null;
    value?: string | null;
    score?: Score;
    section?: string | null;
    /**
     * Set to false to hide field from all views and calculations
     */
    visible?: boolean;
}

