/**
 * Space Zoo Management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InspectionFilter { 
    id?: string | null;
    name?: string | null;
    template?: string | null;
    habitat?: string | null;
    lastAudit?: string | null;
    content?: string | null;
    version?: string | null;
    status?: string | null;
    score?: string | null;
    archived?: boolean | null;
    start?: string | null;
    end?: string | null;
    summary?: string | null;
}

