/**
 * Space Zoo Management API
 *
 * 
 *
 * NOTE: This file is auto generated by openapi-ts-client.
 * https://github.com/fa-krug/openapi-ts-client
 * Do not edit the class manually.
 */
import { Score } from './score';


export interface InspectionCriteriaOut { 
    last: string | null;
    id?: number | null;
    text: string;
    audit_id: number;
    type: string;
    kwargs?: object | null;
    info?: string | null;
    value?: string | null;
    score?: Score;
    section?: string | null;
    visible?: boolean;
}

