/**
 * Space Zoo Management API
 *
 * 
 *
 * NOTE: This file is auto generated by openapi-ts-client.
 * https://github.com/fa-krug/openapi-ts-client
 * Do not edit the class manually.
 */


export interface InspectionFilter { 
    id?: string | null;
    name?: string | null;
    template?: string | null;
    habitat?: string | null;
    lastAudit?: string | null;
    content?: string | null;
    version?: string | null;
    status?: string | null;
    score?: string | null;
    archived?: boolean | null;
    start?: string | null;
    end?: string | null;
    summary?: string | null;
}

