/**
 * Space Zoo Management API
 *
 * 
 *
 * NOTE: This file is auto generated by openapi-ts-client.
 * https://github.com/fa-krug/openapi-ts-client
 * Do not edit the class manually.
 */


export interface NutritionMetricFilter { 
    id?: string | null;
    spanId?: string | null;
    start?: string | null;
    end?: string | null;
    timespanNs?: string | null;
    type?: string | null;
    name?: string | null;
    statement?: string | null;
    httpMetric?: string | null;
}

