/**
 * Space Zoo Management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NutritionMetricOut { 
    id?: number | null;
    spanId?: string | null;
    start?: string | null;
    end?: string | null;
    timespanNs?: number | null;
    type?: string | null;
    name?: string | null;
    statement?: string | null;
    http_metric_id?: number | null;
}

