/**
 * Space Zoo Management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PermitOut { 
    id?: number | null;
    name: string;
    allowed?: boolean | null;
    /**
     * Risk score associated with the license
     */
    riskScore?: number;
    sourceUrl?: string | null;
}

