/**
 * Space Zoo Management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PermitIn { 
    id?: number | null;
    name?: string | null;
    allowed?: boolean | null;
    riskScore?: number | null;
    sourceUrl?: string | null;
}

