/**
 * Space Zoo Management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SupplyIn { 
    id?: number | null;
    purl?: string | null;
    package_id?: number | null;
    version?: string | null;
    image_id?: number | null;
    bomRef?: string | null;
    type?: string | null;
    author?: string | null;
    riskScore?: number | null;
    riskDetails?: string | null;
    licenses?: Array<number> | null;
    depends_on?: Array<number> | null;
    tags?: Array<number> | null;
}

