/**
 * Space Zoo Management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SupplyOut } from './supplyOut';
import { FoodPackageOut } from './foodPackageOut';
import { SupplyCategoryOut } from './supplyCategoryOut';
import { EnclosureNames } from './enclosureNames';
import { VulnerabilityOut } from './vulnerabilityOut';
import { HabitatNames } from './habitatNames';
import { PermitOut } from './permitOut';


export interface SupplyDetails { 
    'package': FoodPackageOut;
    habitat: HabitatNames;
    image: EnclosureNames;
    licenses: Array<PermitOut>;
    tags: Array<SupplyCategoryOut>;
    vulnerabilities: Array<VulnerabilityOut>;
    dependsOn: Array<SupplyOut>;
    isOutdated: boolean;
    hasAllowedVersion: boolean;
    id?: number | null;
    purl?: string | null;
    version?: string | null;
    /**
     * BOM reference identifier for the dependency
     */
    bomRef: string;
    type?: string | null;
    author?: string | null;
    /**
     * Dependency risk score
     */
    riskScore?: number;
    riskDetails?: string | null;
}

