/**
 * Space Zoo Management API
 *
 * 
 *
 * NOTE: This file is auto generated by openapi-ts-client.
 * https://github.com/fa-krug/openapi-ts-client
 * Do not edit the class manually.
 */


export interface SupplyFilter { 
    id?: string | null;
    purl?: string | null;
    package?: string | null;
    version?: string | null;
    image?: string | null;
    bomRef?: string | null;
    type?: string | null;
    author?: string | null;
    riskScore?: string | null;
    riskDetails?: string | null;
    licenses?: Array<number> | null;
    depends_on?: Array<number> | null;
    tags?: Array<number> | null;
}

