/**
 * Space Zoo Management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FoodPackageOut } from './foodPackageOut';
import { SupplyCategoryOut } from './supplyCategoryOut';
import { EnclosureNames } from './enclosureNames';
import { HabitatNames } from './habitatNames';


export interface SupplyOut { 
    'package': FoodPackageOut;
    habitat: HabitatNames;
    image: EnclosureNames;
    tags: Array<SupplyCategoryOut>;
    id?: number | null;
    purl?: string | null;
    version?: string | null;
    /**
     * BOM reference identifier for the dependency
     */
    bomRef: string;
    type?: string | null;
    author?: string | null;
    /**
     * Dependency risk score
     */
    riskScore?: number;
    riskDetails?: string | null;
    licenses: Array<number>;
    depends_on: Array<number>;
}

