/**
 * Space Zoo Management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SecurityRating } from './securityRating';
import { ReliabilityRating } from './reliabilityRating';
import { CodeDuplication } from './codeDuplication';
import { SecurityReviewRating } from './securityReviewRating';
import { MaintainabilityRating } from './maintainabilityRating';
import { TestCoverage } from './testCoverage';


export interface WellnessMetricOut { 
    id?: number | null;
    /**
     * Unique ID of the metric
     */
    metricId?: string;
    datetime?: string | null;
    habitat_id?: number | null;
    linesOfCode?: number | null;
    testCoverage?: TestCoverage | null;
    codeDuplication?: CodeDuplication | null;
    reliabilityRating?: ReliabilityRating | null;
    securityRating?: SecurityRating | null;
    securityReviewRating?: SecurityReviewRating | null;
    maintainabilityRating?: MaintainabilityRating | null;
}

