/**
 * Space Zoo Management API
 *
 * 
 *
 * NOTE: This file is auto generated by openapi-ts-client.
 * https://github.com/fa-krug/openapi-ts-client
 * Do not edit the class manually.
 */
import { CodeDuplication } from './codeDuplication';
import { MaintainabilityRating } from './maintainabilityRating';
import { ReliabilityRating } from './reliabilityRating';
import { SecurityRating } from './securityRating';
import { SecurityReviewRating } from './securityReviewRating';
import { TestCoverage } from './testCoverage';


export interface WellnessMetricOut { 
    id?: number | null;
    metricId?: string;
    datetime?: string | null;
    habitat_id?: number | null;
    linesOfCode?: number | null;
    testCoverage?: TestCoverage | null;
    codeDuplication?: CodeDuplication | null;
    reliabilityRating?: ReliabilityRating | null;
    securityRating?: SecurityRating | null;
    securityReviewRating?: SecurityReviewRating | null;
    maintainabilityRating?: MaintainabilityRating | null;
}

