/**
 * Swagger Petstore - OpenAPI 3.0
 *
 * Contact: apiteam@swagger.io
 *
 * NOTE: This file is auto generated by openapi-ts-client.
 * https://github.com/fa-krug/openapi-ts-client
 * Do not edit the class manually.
 */


export interface ApiResponse { 
    code?: number;
    type?: string;
    message?: string;
}

