/**
 * Swagger Petstore - OpenAPI 3.0
 *
 * Contact: apiteam@swagger.io
 *
 * NOTE: This file is auto generated by openapi-ts-client.
 * https://github.com/fa-krug/openapi-ts-client
 * Do not edit the class manually.
 */
import { Category } from './category';
import { Tag } from './tag';


export interface Pet { 
    id?: number;
    name: string;
    category?: Category;
    photoUrls: Array<string>;
    tags?: Array<Tag>;
    /**
     * pet status in the store
     */
    status?: Pet.StatusEnum;
}
export namespace Pet {
    export const StatusEnum = {
        Available: 'available',
        Pending: 'pending',
        Sold: 'sold'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


