/* tslint:disable */
/* eslint-disable */
/**
 * Space Zoo Management API
 * API for managing the Galactic Space Zoo - home to exotic alien creatures from across the universe
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BehaviorMetricFilter
 */
export interface BehaviorMetricFilter {
    /**
     * Filter by exact match
     * @type {string}
     * @memberof BehaviorMetricFilter
     */
    id?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof BehaviorMetricFilter
     */
    spanId?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof BehaviorMetricFilter
     */
    start?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof BehaviorMetricFilter
     */
    end?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof BehaviorMetricFilter
     */
    timespanNs?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof BehaviorMetricFilter
     */
    httpMetric?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof BehaviorMetricFilter
     */
    name?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof BehaviorMetricFilter
     */
    value?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof BehaviorMetricFilter
     */
    details?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof BehaviorMetricFilter
     */
    createdBy?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof BehaviorMetricFilter
     */
    message?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof BehaviorMetricFilter
     */
    state?: string | null;
}

/**
 * Check if a given object implements the BehaviorMetricFilter interface.
 */
export function instanceOfBehaviorMetricFilter(value: object): value is BehaviorMetricFilter {
    return true;
}

export function BehaviorMetricFilterFromJSON(json: any): BehaviorMetricFilter {
    return BehaviorMetricFilterFromJSONTyped(json, false);
}

export function BehaviorMetricFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): BehaviorMetricFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'spanId': json['spanId'] == null ? undefined : json['spanId'],
        'start': json['start'] == null ? undefined : json['start'],
        'end': json['end'] == null ? undefined : json['end'],
        'timespanNs': json['timespanNs'] == null ? undefined : json['timespanNs'],
        'httpMetric': json['httpMetric'] == null ? undefined : json['httpMetric'],
        'name': json['name'] == null ? undefined : json['name'],
        'value': json['value'] == null ? undefined : json['value'],
        'details': json['details'] == null ? undefined : json['details'],
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'message': json['message'] == null ? undefined : json['message'],
        'state': json['state'] == null ? undefined : json['state'],
    };
}

export function BehaviorMetricFilterToJSON(json: any): BehaviorMetricFilter {
    return BehaviorMetricFilterToJSONTyped(json, false);
}

export function BehaviorMetricFilterToJSONTyped(value?: BehaviorMetricFilter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'spanId': value['spanId'],
        'start': value['start'],
        'end': value['end'],
        'timespanNs': value['timespanNs'],
        'httpMetric': value['httpMetric'],
        'name': value['name'],
        'value': value['value'],
        'details': value['details'],
        'createdBy': value['createdBy'],
        'message': value['message'],
        'state': value['state'],
    };
}

