/* tslint:disable */
/* eslint-disable */
/**
 * Space Zoo Management API
 * API for managing the Galactic Space Zoo - home to exotic alien creatures from across the universe
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BehaviorMetricOut
 */
export interface BehaviorMetricOut {
    /**
     * 
     * @type {number}
     * @memberof BehaviorMetricOut
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof BehaviorMetricOut
     */
    spanId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof BehaviorMetricOut
     */
    start?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof BehaviorMetricOut
     */
    end?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof BehaviorMetricOut
     */
    timespanNs?: number | null;
    /**
     * 
     * @type {number}
     * @memberof BehaviorMetricOut
     */
    httpMetricId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof BehaviorMetricOut
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BehaviorMetricOut
     */
    value?: number | null;
    /**
     * 
     * @type {object}
     * @memberof BehaviorMetricOut
     */
    details?: object | null;
    /**
     * 
     * @type {string}
     * @memberof BehaviorMetricOut
     */
    createdBy?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BehaviorMetricOut
     */
    message?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BehaviorMetricOut
     */
    state?: string | null;
}

/**
 * Check if a given object implements the BehaviorMetricOut interface.
 */
export function instanceOfBehaviorMetricOut(value: object): value is BehaviorMetricOut {
    return true;
}

export function BehaviorMetricOutFromJSON(json: any): BehaviorMetricOut {
    return BehaviorMetricOutFromJSONTyped(json, false);
}

export function BehaviorMetricOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): BehaviorMetricOut {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'spanId': json['spanId'] == null ? undefined : json['spanId'],
        'start': json['start'] == null ? undefined : (new Date(json['start'])),
        'end': json['end'] == null ? undefined : (new Date(json['end'])),
        'timespanNs': json['timespanNs'] == null ? undefined : json['timespanNs'],
        'httpMetricId': json['http_metric_id'] == null ? undefined : json['http_metric_id'],
        'name': json['name'] == null ? undefined : json['name'],
        'value': json['value'] == null ? undefined : json['value'],
        'details': json['details'] == null ? undefined : json['details'],
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'message': json['message'] == null ? undefined : json['message'],
        'state': json['state'] == null ? undefined : json['state'],
    };
}

export function BehaviorMetricOutToJSON(json: any): BehaviorMetricOut {
    return BehaviorMetricOutToJSONTyped(json, false);
}

export function BehaviorMetricOutToJSONTyped(value?: BehaviorMetricOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'spanId': value['spanId'],
        'start': value['start'] == null ? value['start'] : value['start'].toISOString(),
        'end': value['end'] == null ? value['end'] : value['end'].toISOString(),
        'timespanNs': value['timespanNs'],
        'http_metric_id': value['httpMetricId'],
        'name': value['name'],
        'value': value['value'],
        'details': value['details'],
        'createdBy': value['createdBy'],
        'message': value['message'],
        'state': value['state'],
    };
}

