/* tslint:disable */
/* eslint-disable */
/**
 * Space Zoo Management API
 * API for managing the Galactic Space Zoo - home to exotic alien creatures from across the universe
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by openapi-ts-client.
 * https://github.com/fa-krug/openapi-ts-client
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BiomeTypeOut
 */
export interface BiomeTypeOut {
    /**
     * 
     * @type {number}
     * @memberof BiomeTypeOut
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof BiomeTypeOut
     */
    biomeCode: string;
    /**
     * 
     * @type {string}
     * @memberof BiomeTypeOut
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof BiomeTypeOut
     */
    habitatId?: number | null;
}

/**
 * Check if a given object implements the BiomeTypeOut interface.
 */
export function instanceOfBiomeTypeOut(value: object): value is BiomeTypeOut {
    if (!('biomeCode' in value) || value['biomeCode'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function BiomeTypeOutFromJSON(json: any): BiomeTypeOut {
    return BiomeTypeOutFromJSONTyped(json, false);
}

export function BiomeTypeOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): BiomeTypeOut {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'biomeCode': json['biomeCode'],
        'name': json['name'],
        'habitatId': json['habitat_id'] == null ? undefined : json['habitat_id'],
    };
}

export function BiomeTypeOutToJSON(json: any): BiomeTypeOut {
    return BiomeTypeOutToJSONTyped(json, false);
}

export function BiomeTypeOutToJSONTyped(value?: BiomeTypeOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'biomeCode': value['biomeCode'],
        'name': value['name'],
        'habitat_id': value['habitatId'],
    };
}

