/* tslint:disable */
/* eslint-disable */
/**
 * Space Zoo Management API
 * API for managing the Galactic Space Zoo - home to exotic alien creatures from across the universe
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by openapi-ts-client.
 * https://github.com/fa-krug/openapi-ts-client
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BiomeTypeIn
 */
export interface BiomeTypeIn {
    /**
     * 
     * @type {number}
     * @memberof BiomeTypeIn
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof BiomeTypeIn
     */
    biomeCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BiomeTypeIn
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BiomeTypeIn
     */
    habitatId?: number | null;
}

/**
 * Check if a given object implements the BiomeTypeIn interface.
 */
export function instanceOfBiomeTypeIn(value: object): value is BiomeTypeIn {
    return true;
}

export function BiomeTypeInFromJSON(json: any): BiomeTypeIn {
    return BiomeTypeInFromJSONTyped(json, false);
}

export function BiomeTypeInFromJSONTyped(json: any, ignoreDiscriminator: boolean): BiomeTypeIn {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'biomeCode': json['biomeCode'] == null ? undefined : json['biomeCode'],
        'name': json['name'] == null ? undefined : json['name'],
        'habitatId': json['habitat_id'] == null ? undefined : json['habitat_id'],
    };
}

export function BiomeTypeInToJSON(json: any): BiomeTypeIn {
    return BiomeTypeInToJSONTyped(json, false);
}

export function BiomeTypeInToJSONTyped(value?: BiomeTypeIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'biomeCode': value['biomeCode'],
        'name': value['name'],
        'habitat_id': value['habitatId'],
    };
}

