/* tslint:disable */
/* eslint-disable */
/**
 * Space Zoo Management API
 * API for managing the Galactic Space Zoo - home to exotic alien creatures from across the universe
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by openapi-ts-client.
 * https://github.com/fa-krug/openapi-ts-client
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CarePlanOut
 */
export interface CarePlanOut {
    /**
     * 
     * @type {number}
     * @memberof CarePlanOut
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CarePlanOut
     */
    name: string;
    /**
     * 
     * @type {object}
     * @memberof CarePlanOut
     */
    content?: object;
}

/**
 * Check if a given object implements the CarePlanOut interface.
 */
export function instanceOfCarePlanOut(value: object): value is CarePlanOut {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CarePlanOutFromJSON(json: any): CarePlanOut {
    return CarePlanOutFromJSONTyped(json, false);
}

export function CarePlanOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): CarePlanOut {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'content': json['content'] == null ? undefined : json['content'],
    };
}

export function CarePlanOutToJSON(json: any): CarePlanOut {
    return CarePlanOutToJSONTyped(json, false);
}

export function CarePlanOutToJSONTyped(value?: CarePlanOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'content': value['content'],
    };
}

