/* tslint:disable */
/* eslint-disable */
/**
 * Space Zoo Management API
 * API for managing the Galactic Space Zoo - home to exotic alien creatures from across the universe
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by openapi-ts-client.
 * https://github.com/fa-krug/openapi-ts-client
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EnclosureOut
 */
export interface EnclosureOut {
    /**
     * 
     * @type {number}
     * @memberof EnclosureOut
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof EnclosureOut
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof EnclosureOut
     */
    timestamp: Date;
    /**
     * 
     * @type {number}
     * @memberof EnclosureOut
     */
    habitatId?: number | null;
}

/**
 * Check if a given object implements the EnclosureOut interface.
 */
export function instanceOfEnclosureOut(value: object): value is EnclosureOut {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function EnclosureOutFromJSON(json: any): EnclosureOut {
    return EnclosureOutFromJSONTyped(json, false);
}

export function EnclosureOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnclosureOut {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'timestamp': (new Date(json['timestamp'])),
        'habitatId': json['habitat_id'] == null ? undefined : json['habitat_id'],
    };
}

export function EnclosureOutToJSON(json: any): EnclosureOut {
    return EnclosureOutToJSONTyped(json, false);
}

export function EnclosureOutToJSONTyped(value?: EnclosureOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'timestamp': value['timestamp'].toISOString(),
        'habitat_id': value['habitatId'],
    };
}

