/* tslint:disable */
/* eslint-disable */
/**
 * Space Zoo Management API
 * API for managing the Galactic Space Zoo - home to exotic alien creatures from across the universe
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by openapi-ts-client.
 * https://github.com/fa-krug/openapi-ts-client
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EnclosureNames
 */
export interface EnclosureNames {
    /**
     * 
     * @type {number}
     * @memberof EnclosureNames
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof EnclosureNames
     */
    name: string;
}

/**
 * Check if a given object implements the EnclosureNames interface.
 */
export function instanceOfEnclosureNames(value: object): value is EnclosureNames {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function EnclosureNamesFromJSON(json: any): EnclosureNames {
    return EnclosureNamesFromJSONTyped(json, false);
}

export function EnclosureNamesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnclosureNames {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
    };
}

export function EnclosureNamesToJSON(json: any): EnclosureNames {
    return EnclosureNamesToJSONTyped(json, false);
}

export function EnclosureNamesToJSONTyped(value?: EnclosureNames | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

