/* tslint:disable */
/* eslint-disable */
/**
 * Space Zoo Management API
 * API for managing the Galactic Space Zoo - home to exotic alien creatures from across the universe
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EnvironmentReadingOut
 */
export interface EnvironmentReadingOut {
    /**
     * 
     * @type {number}
     * @memberof EnvironmentReadingOut
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof EnvironmentReadingOut
     */
    spanId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof EnvironmentReadingOut
     */
    start?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof EnvironmentReadingOut
     */
    end?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof EnvironmentReadingOut
     */
    timespanNs?: number | null;
    /**
     * 
     * @type {number}
     * @memberof EnvironmentReadingOut
     */
    habitatId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof EnvironmentReadingOut
     */
    url?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EnvironmentReadingOut
     */
    method?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EnvironmentReadingOut
     */
    version?: string | null;
    /**
     * 
     * @type {number}
     * @memberof EnvironmentReadingOut
     */
    statusCode?: number | null;
}

/**
 * Check if a given object implements the EnvironmentReadingOut interface.
 */
export function instanceOfEnvironmentReadingOut(value: object): value is EnvironmentReadingOut {
    return true;
}

export function EnvironmentReadingOutFromJSON(json: any): EnvironmentReadingOut {
    return EnvironmentReadingOutFromJSONTyped(json, false);
}

export function EnvironmentReadingOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnvironmentReadingOut {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'spanId': json['spanId'] == null ? undefined : json['spanId'],
        'start': json['start'] == null ? undefined : (new Date(json['start'])),
        'end': json['end'] == null ? undefined : (new Date(json['end'])),
        'timespanNs': json['timespanNs'] == null ? undefined : json['timespanNs'],
        'habitatId': json['habitat_id'] == null ? undefined : json['habitat_id'],
        'url': json['url'] == null ? undefined : json['url'],
        'method': json['method'] == null ? undefined : json['method'],
        'version': json['version'] == null ? undefined : json['version'],
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
    };
}

export function EnvironmentReadingOutToJSON(json: any): EnvironmentReadingOut {
    return EnvironmentReadingOutToJSONTyped(json, false);
}

export function EnvironmentReadingOutToJSONTyped(value?: EnvironmentReadingOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'spanId': value['spanId'],
        'start': value['start'] == null ? value['start'] : value['start'].toISOString(),
        'end': value['end'] == null ? value['end'] : value['end'].toISOString(),
        'timespanNs': value['timespanNs'],
        'habitat_id': value['habitatId'],
        'url': value['url'],
        'method': value['method'],
        'version': value['version'],
        'statusCode': value['statusCode'],
    };
}

