/* tslint:disable */
/* eslint-disable */
/**
 * Space Zoo Management API
 * API for managing the Galactic Space Zoo - home to exotic alien creatures from across the universe
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EnvironmentReadingFilter
 */
export interface EnvironmentReadingFilter {
    /**
     * Filter by exact match
     * @type {string}
     * @memberof EnvironmentReadingFilter
     */
    id?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof EnvironmentReadingFilter
     */
    spanId?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof EnvironmentReadingFilter
     */
    start?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof EnvironmentReadingFilter
     */
    end?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof EnvironmentReadingFilter
     */
    timespanNs?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof EnvironmentReadingFilter
     */
    habitat?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof EnvironmentReadingFilter
     */
    url?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof EnvironmentReadingFilter
     */
    method?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof EnvironmentReadingFilter
     */
    version?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof EnvironmentReadingFilter
     */
    statusCode?: string | null;
}

/**
 * Check if a given object implements the EnvironmentReadingFilter interface.
 */
export function instanceOfEnvironmentReadingFilter(value: object): value is EnvironmentReadingFilter {
    return true;
}

export function EnvironmentReadingFilterFromJSON(json: any): EnvironmentReadingFilter {
    return EnvironmentReadingFilterFromJSONTyped(json, false);
}

export function EnvironmentReadingFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnvironmentReadingFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'spanId': json['spanId'] == null ? undefined : json['spanId'],
        'start': json['start'] == null ? undefined : json['start'],
        'end': json['end'] == null ? undefined : json['end'],
        'timespanNs': json['timespanNs'] == null ? undefined : json['timespanNs'],
        'habitat': json['habitat'] == null ? undefined : json['habitat'],
        'url': json['url'] == null ? undefined : json['url'],
        'method': json['method'] == null ? undefined : json['method'],
        'version': json['version'] == null ? undefined : json['version'],
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
    };
}

export function EnvironmentReadingFilterToJSON(json: any): EnvironmentReadingFilter {
    return EnvironmentReadingFilterToJSONTyped(json, false);
}

export function EnvironmentReadingFilterToJSONTyped(value?: EnvironmentReadingFilter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'spanId': value['spanId'],
        'start': value['start'],
        'end': value['end'],
        'timespanNs': value['timespanNs'],
        'habitat': value['habitat'],
        'url': value['url'],
        'method': value['method'],
        'version': value['version'],
        'statusCode': value['statusCode'],
    };
}

