/* tslint:disable */
/* eslint-disable */
/**
 * Space Zoo Management API
 * API for managing the Galactic Space Zoo - home to exotic alien creatures from across the universe
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeedingIn
 */
export interface FeedingIn {
    /**
     * 
     * @type {number}
     * @memberof FeedingIn
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof FeedingIn
     */
    value?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FeedingIn
     */
    keeper?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FeedingIn
     */
    creature?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FeedingIn
     */
    priority?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof FeedingIn
     */
    start?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof FeedingIn
     */
    end?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof FeedingIn
     */
    habitatId?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof FeedingIn
     */
    administered?: boolean | null;
    /**
     * 
     * @type {Date}
     * @memberof FeedingIn
     */
    feedingDate?: Date | null;
}

/**
 * Check if a given object implements the FeedingIn interface.
 */
export function instanceOfFeedingIn(value: object): value is FeedingIn {
    return true;
}

export function FeedingInFromJSON(json: any): FeedingIn {
    return FeedingInFromJSONTyped(json, false);
}

export function FeedingInFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedingIn {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'value': json['value'] == null ? undefined : json['value'],
        'keeper': json['keeper'] == null ? undefined : json['keeper'],
        'creature': json['creature'] == null ? undefined : json['creature'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'start': json['start'] == null ? undefined : (new Date(json['start'])),
        'end': json['end'] == null ? undefined : (new Date(json['end'])),
        'habitatId': json['habitat_id'] == null ? undefined : json['habitat_id'],
        'administered': json['administered'] == null ? undefined : json['administered'],
        'feedingDate': json['feedingDate'] == null ? undefined : (new Date(json['feedingDate'])),
    };
}

export function FeedingInToJSON(json: any): FeedingIn {
    return FeedingInToJSONTyped(json, false);
}

export function FeedingInToJSONTyped(value?: FeedingIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'value': value['value'],
        'keeper': value['keeper'],
        'creature': value['creature'],
        'priority': value['priority'],
        'start': value['start'] == null ? value['start'] : value['start'].toISOString().substring(0,10),
        'end': value['end'] == null ? value['end'] : value['end'].toISOString().substring(0,10),
        'habitat_id': value['habitatId'],
        'administered': value['administered'],
        'feedingDate': value['feedingDate'] == null ? value['feedingDate'] : value['feedingDate'].toISOString().substring(0,10),
    };
}

