/* tslint:disable */
/* eslint-disable */
/**
 * Space Zoo Management API
 * API for managing the Galactic Space Zoo - home to exotic alien creatures from across the universe
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FoodPackageFilter
 */
export interface FoodPackageFilter {
    /**
     * 
     * @type {string}
     * @memberof FoodPackageFilter
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FoodPackageFilter
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FoodPackageFilter
     */
    allowedSpecifier?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FoodPackageFilter
     */
    latestVersion?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof FoodPackageFilter
     */
    hidden?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof FoodPackageFilter
     */
    allowed?: boolean | null;
}

/**
 * Check if a given object implements the FoodPackageFilter interface.
 */
export function instanceOfFoodPackageFilter(value: object): value is FoodPackageFilter {
    return true;
}

export function FoodPackageFilterFromJSON(json: any): FoodPackageFilter {
    return FoodPackageFilterFromJSONTyped(json, false);
}

export function FoodPackageFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): FoodPackageFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'allowedSpecifier': json['allowedSpecifier'] == null ? undefined : json['allowedSpecifier'],
        'latestVersion': json['latestVersion'] == null ? undefined : json['latestVersion'],
        'hidden': json['hidden'] == null ? undefined : json['hidden'],
        'allowed': json['allowed'] == null ? undefined : json['allowed'],
    };
}

export function FoodPackageFilterToJSON(json: any): FoodPackageFilter {
    return FoodPackageFilterToJSONTyped(json, false);
}

export function FoodPackageFilterToJSONTyped(value?: FoodPackageFilter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'allowedSpecifier': value['allowedSpecifier'],
        'latestVersion': value['latestVersion'],
        'hidden': value['hidden'],
        'allowed': value['allowed'],
    };
}

