/* tslint:disable */
/* eslint-disable */
/**
 * Space Zoo Management API
 * API for managing the Galactic Space Zoo - home to exotic alien creatures from across the universe
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by openapi-ts-client.
 * https://github.com/fa-krug/openapi-ts-client
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HabitatNames
 */
export interface HabitatNames {
    /**
     * 
     * @type {number}
     * @memberof HabitatNames
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof HabitatNames
     */
    name: string;
}

/**
 * Check if a given object implements the HabitatNames interface.
 */
export function instanceOfHabitatNames(value: object): value is HabitatNames {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function HabitatNamesFromJSON(json: any): HabitatNames {
    return HabitatNamesFromJSONTyped(json, false);
}

export function HabitatNamesFromJSONTyped(json: any, ignoreDiscriminator: boolean): HabitatNames {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
    };
}

export function HabitatNamesToJSON(json: any): HabitatNames {
    return HabitatNamesToJSONTyped(json, false);
}

export function HabitatNamesToJSONTyped(value?: HabitatNames | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

