/* tslint:disable */
/* eslint-disable */
/**
 * Space Zoo Management API
 * API for managing the Galactic Space Zoo - home to exotic alien creatures from across the universe
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OriginPlanetIn } from './OriginPlanetIn';
import {
    OriginPlanetInFromJSON,
    OriginPlanetInFromJSONTyped,
    OriginPlanetInToJSON,
    OriginPlanetInToJSONTyped,
} from './OriginPlanetIn';
import type { BiomeTypeIn } from './BiomeTypeIn';
import {
    BiomeTypeInFromJSON,
    BiomeTypeInFromJSONTyped,
    BiomeTypeInToJSON,
    BiomeTypeInToJSONTyped,
} from './BiomeTypeIn';
import type { EnclosureIn } from './EnclosureIn';
import {
    EnclosureInFromJSON,
    EnclosureInFromJSONTyped,
    EnclosureInToJSON,
    EnclosureInToJSONTyped,
} from './EnclosureIn';

/**
 * 
 * @export
 * @interface HabitatIn
 */
export interface HabitatIn {
    /**
     * 
     * @type {Array<OriginPlanetIn>}
     * @memberof HabitatIn
     */
    originPlanets: Array<OriginPlanetIn>;
    /**
     * 
     * @type {Array<BiomeTypeIn>}
     * @memberof HabitatIn
     */
    biomeTypes: Array<BiomeTypeIn>;
    /**
     * 
     * @type {Array<EnclosureIn>}
     * @memberof HabitatIn
     */
    enclosures: Array<EnclosureIn>;
    /**
     * 
     * @type {number}
     * @memberof HabitatIn
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof HabitatIn
     */
    name?: string | null;
}

/**
 * Check if a given object implements the HabitatIn interface.
 */
export function instanceOfHabitatIn(value: object): value is HabitatIn {
    if (!('originPlanets' in value) || value['originPlanets'] === undefined) return false;
    if (!('biomeTypes' in value) || value['biomeTypes'] === undefined) return false;
    if (!('enclosures' in value) || value['enclosures'] === undefined) return false;
    return true;
}

export function HabitatInFromJSON(json: any): HabitatIn {
    return HabitatInFromJSONTyped(json, false);
}

export function HabitatInFromJSONTyped(json: any, ignoreDiscriminator: boolean): HabitatIn {
    if (json == null) {
        return json;
    }
    return {
        
        'originPlanets': ((json['originPlanets'] as Array<any>).map(OriginPlanetInFromJSON)),
        'biomeTypes': ((json['biomeTypes'] as Array<any>).map(BiomeTypeInFromJSON)),
        'enclosures': ((json['enclosures'] as Array<any>).map(EnclosureInFromJSON)),
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function HabitatInToJSON(json: any): HabitatIn {
    return HabitatInToJSONTyped(json, false);
}

export function HabitatInToJSONTyped(value?: HabitatIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'originPlanets': ((value['originPlanets'] as Array<any>).map(OriginPlanetInToJSON)),
        'biomeTypes': ((value['biomeTypes'] as Array<any>).map(BiomeTypeInToJSON)),
        'enclosures': ((value['enclosures'] as Array<any>).map(EnclosureInToJSON)),
        'id': value['id'],
        'name': value['name'],
    };
}

