/* tslint:disable */
/* eslint-disable */
/**
 * Space Zoo Management API
 * API for managing the Galactic Space Zoo - home to exotic alien creatures from across the universe
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by openapi-ts-client.
 * https://github.com/fa-krug/openapi-ts-client
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InspectionFilter
 */
export interface InspectionFilter {
    /**
     * Filter by exact match
     * @type {string}
     * @memberof InspectionFilter
     */
    id?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof InspectionFilter
     */
    name?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof InspectionFilter
     */
    template?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof InspectionFilter
     */
    habitat?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof InspectionFilter
     */
    lastAudit?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof InspectionFilter
     */
    content?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof InspectionFilter
     */
    version?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof InspectionFilter
     */
    status?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof InspectionFilter
     */
    score?: string | null;
    /**
     * Filter by exact match
     * @type {boolean}
     * @memberof InspectionFilter
     */
    archived?: boolean | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof InspectionFilter
     */
    start?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof InspectionFilter
     */
    end?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof InspectionFilter
     */
    summary?: string | null;
}

/**
 * Check if a given object implements the InspectionFilter interface.
 */
export function instanceOfInspectionFilter(value: object): value is InspectionFilter {
    return true;
}

export function InspectionFilterFromJSON(json: any): InspectionFilter {
    return InspectionFilterFromJSONTyped(json, false);
}

export function InspectionFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): InspectionFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'template': json['template'] == null ? undefined : json['template'],
        'habitat': json['habitat'] == null ? undefined : json['habitat'],
        'lastAudit': json['lastAudit'] == null ? undefined : json['lastAudit'],
        'content': json['content'] == null ? undefined : json['content'],
        'version': json['version'] == null ? undefined : json['version'],
        'status': json['status'] == null ? undefined : json['status'],
        'score': json['score'] == null ? undefined : json['score'],
        'archived': json['archived'] == null ? undefined : json['archived'],
        'start': json['start'] == null ? undefined : json['start'],
        'end': json['end'] == null ? undefined : json['end'],
        'summary': json['summary'] == null ? undefined : json['summary'],
    };
}

export function InspectionFilterToJSON(json: any): InspectionFilter {
    return InspectionFilterToJSONTyped(json, false);
}

export function InspectionFilterToJSONTyped(value?: InspectionFilter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'template': value['template'],
        'habitat': value['habitat'],
        'lastAudit': value['lastAudit'],
        'content': value['content'],
        'version': value['version'],
        'status': value['status'],
        'score': value['score'],
        'archived': value['archived'],
        'start': value['start'],
        'end': value['end'],
        'summary': value['summary'],
    };
}

