/* tslint:disable */
/* eslint-disable */
/**
 * Space Zoo Management API
 * API for managing the Galactic Space Zoo - home to exotic alien creatures from across the universe
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Score1 } from './Score1';
import {
    Score1FromJSON,
    Score1FromJSONTyped,
    Score1ToJSON,
    Score1ToJSONTyped,
} from './Score1';

/**
 * 
 * @export
 * @interface InspectionCriteriaIn
 */
export interface InspectionCriteriaIn {
    /**
     * 
     * @type {number}
     * @memberof InspectionCriteriaIn
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof InspectionCriteriaIn
     */
    text?: string | null;
    /**
     * 
     * @type {number}
     * @memberof InspectionCriteriaIn
     */
    auditId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof InspectionCriteriaIn
     */
    type?: string | null;
    /**
     * 
     * @type {object}
     * @memberof InspectionCriteriaIn
     */
    kwargs?: object | null;
    /**
     * 
     * @type {string}
     * @memberof InspectionCriteriaIn
     */
    info?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InspectionCriteriaIn
     */
    value?: string | null;
    /**
     * 
     * @type {Score1}
     * @memberof InspectionCriteriaIn
     */
    score?: Score1 | null;
    /**
     * 
     * @type {string}
     * @memberof InspectionCriteriaIn
     */
    section?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof InspectionCriteriaIn
     */
    visible?: boolean | null;
}

/**
 * Check if a given object implements the InspectionCriteriaIn interface.
 */
export function instanceOfInspectionCriteriaIn(value: object): value is InspectionCriteriaIn {
    return true;
}

export function InspectionCriteriaInFromJSON(json: any): InspectionCriteriaIn {
    return InspectionCriteriaInFromJSONTyped(json, false);
}

export function InspectionCriteriaInFromJSONTyped(json: any, ignoreDiscriminator: boolean): InspectionCriteriaIn {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'text': json['text'] == null ? undefined : json['text'],
        'auditId': json['audit_id'] == null ? undefined : json['audit_id'],
        'type': json['type'] == null ? undefined : json['type'],
        'kwargs': json['kwargs'] == null ? undefined : json['kwargs'],
        'info': json['info'] == null ? undefined : json['info'],
        'value': json['value'] == null ? undefined : json['value'],
        'score': json['score'] == null ? undefined : Score1FromJSON(json['score']),
        'section': json['section'] == null ? undefined : json['section'],
        'visible': json['visible'] == null ? undefined : json['visible'],
    };
}

export function InspectionCriteriaInToJSON(json: any): InspectionCriteriaIn {
    return InspectionCriteriaInToJSONTyped(json, false);
}

export function InspectionCriteriaInToJSONTyped(value?: InspectionCriteriaIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'text': value['text'],
        'audit_id': value['auditId'],
        'type': value['type'],
        'kwargs': value['kwargs'],
        'info': value['info'],
        'value': value['value'],
        'score': Score1ToJSON(value['score']),
        'section': value['section'],
        'visible': value['visible'],
    };
}

