/* tslint:disable */
/* eslint-disable */
/**
 * Space Zoo Management API
 * API for managing the Galactic Space Zoo - home to exotic alien creatures from across the universe
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InspectionIssue
 */
export interface InspectionIssue {
    /**
     * 
     * @type {string}
     * @memberof InspectionIssue
     */
    creature: string;
    /**
     * 
     * @type {number}
     * @memberof InspectionIssue
     */
    score: number;
    /**
     * 
     * @type {string}
     * @memberof InspectionIssue
     */
    value: string;
}

/**
 * Check if a given object implements the InspectionIssue interface.
 */
export function instanceOfInspectionIssue(value: object): value is InspectionIssue {
    if (!('creature' in value) || value['creature'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function InspectionIssueFromJSON(json: any): InspectionIssue {
    return InspectionIssueFromJSONTyped(json, false);
}

export function InspectionIssueFromJSONTyped(json: any, ignoreDiscriminator: boolean): InspectionIssue {
    if (json == null) {
        return json;
    }
    return {
        
        'creature': json['creature'],
        'score': json['score'],
        'value': json['value'],
    };
}

export function InspectionIssueToJSON(json: any): InspectionIssue {
    return InspectionIssueToJSONTyped(json, false);
}

export function InspectionIssueToJSONTyped(value?: InspectionIssue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'creature': value['creature'],
        'score': value['score'],
        'value': value['value'],
    };
}

