/* tslint:disable */
/* eslint-disable */
/**
 * Space Zoo Management API
 * API for managing the Galactic Space Zoo - home to exotic alien creatures from across the universe
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by openapi-ts-client.
 * https://github.com/fa-krug/openapi-ts-client
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InspectionRanking
 */
export interface InspectionRanking {
    /**
     * 
     * @type {number}
     * @memberof InspectionRanking
     */
    place: number;
    /**
     * 
     * @type {string}
     * @memberof InspectionRanking
     */
    habitat: string;
    /**
     * 
     * @type {number}
     * @memberof InspectionRanking
     */
    score: number;
    /**
     * 
     * @type {number}
     * @memberof InspectionRanking
     */
    lastScore: number | null;
    /**
     * 
     * @type {string}
     * @memberof InspectionRanking
     */
    changes: string;
    /**
     * 
     * @type {string}
     * @memberof InspectionRanking
     */
    template: string;
}

/**
 * Check if a given object implements the InspectionRanking interface.
 */
export function instanceOfInspectionRanking(value: object): value is InspectionRanking {
    if (!('place' in value) || value['place'] === undefined) return false;
    if (!('habitat' in value) || value['habitat'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    if (!('lastScore' in value) || value['lastScore'] === undefined) return false;
    if (!('changes' in value) || value['changes'] === undefined) return false;
    if (!('template' in value) || value['template'] === undefined) return false;
    return true;
}

export function InspectionRankingFromJSON(json: any): InspectionRanking {
    return InspectionRankingFromJSONTyped(json, false);
}

export function InspectionRankingFromJSONTyped(json: any, ignoreDiscriminator: boolean): InspectionRanking {
    if (json == null) {
        return json;
    }
    return {
        
        'place': json['place'],
        'habitat': json['habitat'],
        'score': json['score'],
        'lastScore': json['lastScore'],
        'changes': json['changes'],
        'template': json['template'],
    };
}

export function InspectionRankingToJSON(json: any): InspectionRanking {
    return InspectionRankingToJSONTyped(json, false);
}

export function InspectionRankingToJSONTyped(value?: InspectionRanking | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'place': value['place'],
        'habitat': value['habitat'],
        'score': value['score'],
        'lastScore': value['lastScore'],
        'changes': value['changes'],
        'template': value['template'],
    };
}

