/* tslint:disable */
/* eslint-disable */
/**
 * Space Zoo Management API
 * API for managing the Galactic Space Zoo - home to exotic alien creatures from across the universe
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CodeQuality } from './CodeQuality';
import {
    CodeQualityFromJSON,
    CodeQualityFromJSONTyped,
    CodeQualityToJSON,
    CodeQualityToJSONTyped,
} from './CodeQuality';

/**
 * 
 * @export
 * @interface MigrationMetricIn
 */
export interface MigrationMetricIn {
    /**
     * 
     * @type {number}
     * @memberof MigrationMetricIn
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof MigrationMetricIn
     */
    metricId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof MigrationMetricIn
     */
    datetime?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof MigrationMetricIn
     */
    habitatId?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof MigrationMetricIn
     */
    lastCommit?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof MigrationMetricIn
     */
    commits?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof MigrationMetricIn
     */
    lastRelease?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof MigrationMetricIn
     */
    openIssues?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MigrationMetricIn
     */
    closedIssues?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MigrationMetricIn
     */
    featureIssues?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MigrationMetricIn
     */
    closedFeatureIssues?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MigrationMetricIn
     */
    bugIssues?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MigrationMetricIn
     */
    closedBugIssues?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MigrationMetricIn
     */
    bugTtl?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MigrationMetricIn
     */
    doingTime?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MigrationMetricIn
     */
    reviewTime?: number | null;
    /**
     * 
     * @type {CodeQuality}
     * @memberof MigrationMetricIn
     */
    codeQuality?: CodeQuality | null;
}

/**
 * Check if a given object implements the MigrationMetricIn interface.
 */
export function instanceOfMigrationMetricIn(value: object): value is MigrationMetricIn {
    return true;
}

export function MigrationMetricInFromJSON(json: any): MigrationMetricIn {
    return MigrationMetricInFromJSONTyped(json, false);
}

export function MigrationMetricInFromJSONTyped(json: any, ignoreDiscriminator: boolean): MigrationMetricIn {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'metricId': json['metricId'] == null ? undefined : json['metricId'],
        'datetime': json['datetime'] == null ? undefined : (new Date(json['datetime'])),
        'habitatId': json['habitat_id'] == null ? undefined : json['habitat_id'],
        'lastCommit': json['lastCommit'] == null ? undefined : (new Date(json['lastCommit'])),
        'commits': json['commits'] == null ? undefined : json['commits'],
        'lastRelease': json['lastRelease'] == null ? undefined : (new Date(json['lastRelease'])),
        'openIssues': json['openIssues'] == null ? undefined : json['openIssues'],
        'closedIssues': json['closedIssues'] == null ? undefined : json['closedIssues'],
        'featureIssues': json['featureIssues'] == null ? undefined : json['featureIssues'],
        'closedFeatureIssues': json['closedFeatureIssues'] == null ? undefined : json['closedFeatureIssues'],
        'bugIssues': json['bugIssues'] == null ? undefined : json['bugIssues'],
        'closedBugIssues': json['closedBugIssues'] == null ? undefined : json['closedBugIssues'],
        'bugTtl': json['bugTtl'] == null ? undefined : json['bugTtl'],
        'doingTime': json['doingTime'] == null ? undefined : json['doingTime'],
        'reviewTime': json['reviewTime'] == null ? undefined : json['reviewTime'],
        'codeQuality': json['codeQuality'] == null ? undefined : CodeQualityFromJSON(json['codeQuality']),
    };
}

export function MigrationMetricInToJSON(json: any): MigrationMetricIn {
    return MigrationMetricInToJSONTyped(json, false);
}

export function MigrationMetricInToJSONTyped(value?: MigrationMetricIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'metricId': value['metricId'],
        'datetime': value['datetime'] == null ? value['datetime'] : value['datetime'].toISOString(),
        'habitat_id': value['habitatId'],
        'lastCommit': value['lastCommit'] == null ? value['lastCommit'] : value['lastCommit'].toISOString(),
        'commits': value['commits'],
        'lastRelease': value['lastRelease'] == null ? value['lastRelease'] : value['lastRelease'].toISOString(),
        'openIssues': value['openIssues'],
        'closedIssues': value['closedIssues'],
        'featureIssues': value['featureIssues'],
        'closedFeatureIssues': value['closedFeatureIssues'],
        'bugIssues': value['bugIssues'],
        'closedBugIssues': value['closedBugIssues'],
        'bugTtl': value['bugTtl'],
        'doingTime': value['doingTime'],
        'reviewTime': value['reviewTime'],
        'codeQuality': CodeQualityToJSON(value['codeQuality']),
    };
}

