/* tslint:disable */
/* eslint-disable */
/**
 * Space Zoo Management API
 * API for managing the Galactic Space Zoo - home to exotic alien creatures from across the universe
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NutritionMetricOut
 */
export interface NutritionMetricOut {
    /**
     * 
     * @type {number}
     * @memberof NutritionMetricOut
     */
    id?: number | null;
    /**
     * ID of the original span
     * @type {string}
     * @memberof NutritionMetricOut
     */
    spanId?: string | null;
    /**
     * Timestamp when the request came in
     * @type {Date}
     * @memberof NutritionMetricOut
     */
    start?: Date | null;
    /**
     * Timestamp when the response was send out
     * @type {Date}
     * @memberof NutritionMetricOut
     */
    end?: Date | null;
    /**
     * Processing timespan in nanoseconds
     * @type {number}
     * @memberof NutritionMetricOut
     */
    timespanNs?: number | null;
    /**
     * Type of database
     * @type {string}
     * @memberof NutritionMetricOut
     */
    type?: string | null;
    /**
     * Name of the database if present
     * @type {string}
     * @memberof NutritionMetricOut
     */
    name?: string | null;
    /**
     * Full statement
     * @type {string}
     * @memberof NutritionMetricOut
     */
    statement?: string | null;
    /**
     * 
     * @type {number}
     * @memberof NutritionMetricOut
     */
    httpMetricId?: number | null;
}

/**
 * Check if a given object implements the NutritionMetricOut interface.
 */
export function instanceOfNutritionMetricOut(value: object): value is NutritionMetricOut {
    return true;
}

export function NutritionMetricOutFromJSON(json: any): NutritionMetricOut {
    return NutritionMetricOutFromJSONTyped(json, false);
}

export function NutritionMetricOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): NutritionMetricOut {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'spanId': json['spanId'] == null ? undefined : json['spanId'],
        'start': json['start'] == null ? undefined : (new Date(json['start'])),
        'end': json['end'] == null ? undefined : (new Date(json['end'])),
        'timespanNs': json['timespanNs'] == null ? undefined : json['timespanNs'],
        'type': json['type'] == null ? undefined : json['type'],
        'name': json['name'] == null ? undefined : json['name'],
        'statement': json['statement'] == null ? undefined : json['statement'],
        'httpMetricId': json['http_metric_id'] == null ? undefined : json['http_metric_id'],
    };
}

export function NutritionMetricOutToJSON(json: any): NutritionMetricOut {
    return NutritionMetricOutToJSONTyped(json, false);
}

export function NutritionMetricOutToJSONTyped(value?: NutritionMetricOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'spanId': value['spanId'],
        'start': value['start'] == null ? value['start'] : value['start'].toISOString(),
        'end': value['end'] == null ? value['end'] : value['end'].toISOString(),
        'timespanNs': value['timespanNs'],
        'type': value['type'],
        'name': value['name'],
        'statement': value['statement'],
        'http_metric_id': value['httpMetricId'],
    };
}

