/* tslint:disable */
/* eslint-disable */
/**
 * Space Zoo Management API
 * API for managing the Galactic Space Zoo - home to exotic alien creatures from across the universe
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NutritionMetricFilter
 */
export interface NutritionMetricFilter {
    /**
     * Filter by exact match
     * @type {string}
     * @memberof NutritionMetricFilter
     */
    id?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof NutritionMetricFilter
     */
    spanId?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof NutritionMetricFilter
     */
    start?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof NutritionMetricFilter
     */
    end?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof NutritionMetricFilter
     */
    timespanNs?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof NutritionMetricFilter
     */
    type?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof NutritionMetricFilter
     */
    name?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof NutritionMetricFilter
     */
    statement?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof NutritionMetricFilter
     */
    httpMetric?: string | null;
}

/**
 * Check if a given object implements the NutritionMetricFilter interface.
 */
export function instanceOfNutritionMetricFilter(value: object): value is NutritionMetricFilter {
    return true;
}

export function NutritionMetricFilterFromJSON(json: any): NutritionMetricFilter {
    return NutritionMetricFilterFromJSONTyped(json, false);
}

export function NutritionMetricFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): NutritionMetricFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'spanId': json['spanId'] == null ? undefined : json['spanId'],
        'start': json['start'] == null ? undefined : json['start'],
        'end': json['end'] == null ? undefined : json['end'],
        'timespanNs': json['timespanNs'] == null ? undefined : json['timespanNs'],
        'type': json['type'] == null ? undefined : json['type'],
        'name': json['name'] == null ? undefined : json['name'],
        'statement': json['statement'] == null ? undefined : json['statement'],
        'httpMetric': json['httpMetric'] == null ? undefined : json['httpMetric'],
    };
}

export function NutritionMetricFilterToJSON(json: any): NutritionMetricFilter {
    return NutritionMetricFilterToJSONTyped(json, false);
}

export function NutritionMetricFilterToJSONTyped(value?: NutritionMetricFilter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'spanId': value['spanId'],
        'start': value['start'],
        'end': value['end'],
        'timespanNs': value['timespanNs'],
        'type': value['type'],
        'name': value['name'],
        'statement': value['statement'],
        'httpMetric': value['httpMetric'],
    };
}

