/* tslint:disable */
/* eslint-disable */
/**
 * Space Zoo Management API
 * API for managing the Galactic Space Zoo - home to exotic alien creatures from across the universe
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OriginPlanetFilter
 */
export interface OriginPlanetFilter {
    /**
     * Filter by exact match
     * @type {string}
     * @memberof OriginPlanetFilter
     */
    id?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof OriginPlanetFilter
     */
    name?: string | null;
    /**
     * Filter by exact match
     * @type {string}
     * @memberof OriginPlanetFilter
     */
    habitat?: string | null;
}

/**
 * Check if a given object implements the OriginPlanetFilter interface.
 */
export function instanceOfOriginPlanetFilter(value: object): value is OriginPlanetFilter {
    return true;
}

export function OriginPlanetFilterFromJSON(json: any): OriginPlanetFilter {
    return OriginPlanetFilterFromJSONTyped(json, false);
}

export function OriginPlanetFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): OriginPlanetFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'habitat': json['habitat'] == null ? undefined : json['habitat'],
    };
}

export function OriginPlanetFilterToJSON(json: any): OriginPlanetFilter {
    return OriginPlanetFilterToJSONTyped(json, false);
}

export function OriginPlanetFilterToJSONTyped(value?: OriginPlanetFilter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'habitat': value['habitat'],
    };
}

