/* tslint:disable */
/* eslint-disable */
/**
 * Space Zoo Management API
 * API for managing the Galactic Space Zoo - home to exotic alien creatures from across the universe
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by openapi-ts-client.
 * https://github.com/fa-krug/openapi-ts-client
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OriginPlanetIn
 */
export interface OriginPlanetIn {
    /**
     * 
     * @type {number}
     * @memberof OriginPlanetIn
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof OriginPlanetIn
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof OriginPlanetIn
     */
    habitatId?: number | null;
}

/**
 * Check if a given object implements the OriginPlanetIn interface.
 */
export function instanceOfOriginPlanetIn(value: object): value is OriginPlanetIn {
    return true;
}

export function OriginPlanetInFromJSON(json: any): OriginPlanetIn {
    return OriginPlanetInFromJSONTyped(json, false);
}

export function OriginPlanetInFromJSONTyped(json: any, ignoreDiscriminator: boolean): OriginPlanetIn {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'habitatId': json['habitat_id'] == null ? undefined : json['habitat_id'],
    };
}

export function OriginPlanetInToJSON(json: any): OriginPlanetIn {
    return OriginPlanetInToJSONTyped(json, false);
}

export function OriginPlanetInToJSONTyped(value?: OriginPlanetIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'habitat_id': value['habitatId'],
    };
}

