/* tslint:disable */
/* eslint-disable */
/**
 * Space Zoo Management API
 * API for managing the Galactic Space Zoo - home to exotic alien creatures from across the universe
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PermitFilter
 */
export interface PermitFilter {
    /**
     * 
     * @type {string}
     * @memberof PermitFilter
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PermitFilter
     */
    name?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PermitFilter
     */
    allowed?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof PermitFilter
     */
    riskScore?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PermitFilter
     */
    sourceUrl?: string | null;
}

/**
 * Check if a given object implements the PermitFilter interface.
 */
export function instanceOfPermitFilter(value: object): value is PermitFilter {
    return true;
}

export function PermitFilterFromJSON(json: any): PermitFilter {
    return PermitFilterFromJSONTyped(json, false);
}

export function PermitFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermitFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'allowed': json['allowed'] == null ? undefined : json['allowed'],
        'riskScore': json['riskScore'] == null ? undefined : json['riskScore'],
        'sourceUrl': json['sourceUrl'] == null ? undefined : json['sourceUrl'],
    };
}

export function PermitFilterToJSON(json: any): PermitFilter {
    return PermitFilterToJSONTyped(json, false);
}

export function PermitFilterToJSONTyped(value?: PermitFilter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'allowed': value['allowed'],
        'riskScore': value['riskScore'],
        'sourceUrl': value['sourceUrl'],
    };
}

