/* tslint:disable */
/* eslint-disable */
/**
 * Space Zoo Management API
 * API for managing the Galactic Space Zoo - home to exotic alien creatures from across the universe
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by openapi-ts-client.
 * https://github.com/fa-krug/openapi-ts-client
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * reliability_rating in main branch
 * @export
 * @interface ReliabilityRating
 */
export interface ReliabilityRating {
}

/**
 * Check if a given object implements the ReliabilityRating interface.
 */
export function instanceOfReliabilityRating(value: object): value is ReliabilityRating {
    return true;
}

export function ReliabilityRatingFromJSON(json: any): ReliabilityRating {
    return ReliabilityRatingFromJSONTyped(json, false);
}

export function ReliabilityRatingFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReliabilityRating {
    return json;
}

export function ReliabilityRatingToJSON(json: any): ReliabilityRating {
    return ReliabilityRatingToJSONTyped(json, false);
}

export function ReliabilityRatingToJSONTyped(value?: ReliabilityRating | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

