/* tslint:disable */
/* eslint-disable */
/**
 * Space Zoo Management API
 * API for managing the Galactic Space Zoo - home to exotic alien creatures from across the universe
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by openapi-ts-client.
 * https://github.com/fa-krug/openapi-ts-client
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Schema for operation results.
 * @export
 * @interface ResultSchema
 */
export interface ResultSchema {
    /**
     * 
     * @type {string}
     * @memberof ResultSchema
     */
    detail: string;
}

/**
 * Check if a given object implements the ResultSchema interface.
 */
export function instanceOfResultSchema(value: object): value is ResultSchema {
    if (!('detail' in value) || value['detail'] === undefined) return false;
    return true;
}

export function ResultSchemaFromJSON(json: any): ResultSchema {
    return ResultSchemaFromJSONTyped(json, false);
}

export function ResultSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'detail': json['detail'],
    };
}

export function ResultSchemaToJSON(json: any): ResultSchema {
    return ResultSchemaToJSONTyped(json, false);
}

export function ResultSchemaToJSONTyped(value?: ResultSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'detail': value['detail'],
    };
}

