/* tslint:disable */
/* eslint-disable */
/**
 * Space Zoo Management API
 * API for managing the Galactic Space Zoo - home to exotic alien creatures from across the universe
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * security_review_rating in main branch
 * @export
 * @interface SecurityReviewRating
 */
export interface SecurityReviewRating {
}

/**
 * Check if a given object implements the SecurityReviewRating interface.
 */
export function instanceOfSecurityReviewRating(value: object): value is SecurityReviewRating {
    return true;
}

export function SecurityReviewRatingFromJSON(json: any): SecurityReviewRating {
    return SecurityReviewRatingFromJSONTyped(json, false);
}

export function SecurityReviewRatingFromJSONTyped(json: any, ignoreDiscriminator: boolean): SecurityReviewRating {
    return json;
}

export function SecurityReviewRatingToJSON(json: any): SecurityReviewRating {
    return SecurityReviewRatingToJSONTyped(json, false);
}

export function SecurityReviewRatingToJSONTyped(value?: SecurityReviewRating | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

