/* tslint:disable */
/* eslint-disable */
/**
 * Space Zoo Management API
 * API for managing the Galactic Space Zoo - home to exotic alien creatures from across the universe
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by openapi-ts-client.
 * https://github.com/fa-krug/openapi-ts-client
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FoodPackageOut } from './FoodPackageOut';
import {
    FoodPackageOutFromJSON,
    FoodPackageOutFromJSONTyped,
    FoodPackageOutToJSON,
    FoodPackageOutToJSONTyped,
} from './FoodPackageOut';
import type { HabitatNames } from './HabitatNames';
import {
    HabitatNamesFromJSON,
    HabitatNamesFromJSONTyped,
    HabitatNamesToJSON,
    HabitatNamesToJSONTyped,
} from './HabitatNames';
import type { EnclosureNames } from './EnclosureNames';
import {
    EnclosureNamesFromJSON,
    EnclosureNamesFromJSONTyped,
    EnclosureNamesToJSON,
    EnclosureNamesToJSONTyped,
} from './EnclosureNames';
import type { PermitOut } from './PermitOut';
import {
    PermitOutFromJSON,
    PermitOutFromJSONTyped,
    PermitOutToJSON,
    PermitOutToJSONTyped,
} from './PermitOut';
import type { SupplyCategoryOut } from './SupplyCategoryOut';
import {
    SupplyCategoryOutFromJSON,
    SupplyCategoryOutFromJSONTyped,
    SupplyCategoryOutToJSON,
    SupplyCategoryOutToJSONTyped,
} from './SupplyCategoryOut';
import type { VulnerabilityOut } from './VulnerabilityOut';
import {
    VulnerabilityOutFromJSON,
    VulnerabilityOutFromJSONTyped,
    VulnerabilityOutToJSON,
    VulnerabilityOutToJSONTyped,
} from './VulnerabilityOut';
import type { SupplyOut } from './SupplyOut';
import {
    SupplyOutFromJSON,
    SupplyOutFromJSONTyped,
    SupplyOutToJSON,
    SupplyOutToJSONTyped,
} from './SupplyOut';

/**
 * 
 * @export
 * @interface SupplyDetails
 */
export interface SupplyDetails {
    /**
     * 
     * @type {FoodPackageOut}
     * @memberof SupplyDetails
     */
    _package: FoodPackageOut;
    /**
     * 
     * @type {HabitatNames}
     * @memberof SupplyDetails
     */
    habitat: HabitatNames;
    /**
     * 
     * @type {EnclosureNames}
     * @memberof SupplyDetails
     */
    image: EnclosureNames;
    /**
     * 
     * @type {Array<PermitOut>}
     * @memberof SupplyDetails
     */
    licenses: Array<PermitOut>;
    /**
     * 
     * @type {Array<SupplyCategoryOut>}
     * @memberof SupplyDetails
     */
    tags: Array<SupplyCategoryOut>;
    /**
     * 
     * @type {Array<VulnerabilityOut>}
     * @memberof SupplyDetails
     */
    vulnerabilities: Array<VulnerabilityOut>;
    /**
     * 
     * @type {Array<SupplyOut>}
     * @memberof SupplyDetails
     */
    dependsOn: Array<SupplyOut>;
    /**
     * 
     * @type {boolean}
     * @memberof SupplyDetails
     */
    isOutdated: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SupplyDetails
     */
    hasAllowedVersion: boolean;
    /**
     * 
     * @type {number}
     * @memberof SupplyDetails
     */
    id?: number | null;
    /**
     * unique overall identifier for the dependency
     * @type {string}
     * @memberof SupplyDetails
     */
    purl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SupplyDetails
     */
    version?: string | null;
    /**
     * BOM reference identifier for the dependency
     * @type {string}
     * @memberof SupplyDetails
     */
    bomRef: string;
    /**
     * Type of the dependency (e.g., library, tool)
     * @type {string}
     * @memberof SupplyDetails
     */
    type?: string | null;
    /**
     * Author or vendor of the dependency
     * @type {string}
     * @memberof SupplyDetails
     */
    author?: string | null;
    /**
     * Dependency risk score
     * @type {number}
     * @memberof SupplyDetails
     */
    riskScore?: number;
    /**
     * Details about the risk score
     * @type {string}
     * @memberof SupplyDetails
     */
    riskDetails?: string | null;
}

/**
 * Check if a given object implements the SupplyDetails interface.
 */
export function instanceOfSupplyDetails(value: object): value is SupplyDetails {
    if (!('_package' in value) || value['_package'] === undefined) return false;
    if (!('habitat' in value) || value['habitat'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    if (!('licenses' in value) || value['licenses'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    if (!('vulnerabilities' in value) || value['vulnerabilities'] === undefined) return false;
    if (!('dependsOn' in value) || value['dependsOn'] === undefined) return false;
    if (!('isOutdated' in value) || value['isOutdated'] === undefined) return false;
    if (!('hasAllowedVersion' in value) || value['hasAllowedVersion'] === undefined) return false;
    if (!('bomRef' in value) || value['bomRef'] === undefined) return false;
    return true;
}

export function SupplyDetailsFromJSON(json: any): SupplyDetails {
    return SupplyDetailsFromJSONTyped(json, false);
}

export function SupplyDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SupplyDetails {
    if (json == null) {
        return json;
    }
    return {
        
        '_package': FoodPackageOutFromJSON(json['package']),
        'habitat': HabitatNamesFromJSON(json['habitat']),
        'image': EnclosureNamesFromJSON(json['image']),
        'licenses': ((json['licenses'] as Array<any>).map(PermitOutFromJSON)),
        'tags': ((json['tags'] as Array<any>).map(SupplyCategoryOutFromJSON)),
        'vulnerabilities': ((json['vulnerabilities'] as Array<any>).map(VulnerabilityOutFromJSON)),
        'dependsOn': ((json['dependsOn'] as Array<any>).map(SupplyOutFromJSON)),
        'isOutdated': json['isOutdated'],
        'hasAllowedVersion': json['hasAllowedVersion'],
        'id': json['id'] == null ? undefined : json['id'],
        'purl': json['purl'] == null ? undefined : json['purl'],
        'version': json['version'] == null ? undefined : json['version'],
        'bomRef': json['bomRef'],
        'type': json['type'] == null ? undefined : json['type'],
        'author': json['author'] == null ? undefined : json['author'],
        'riskScore': json['riskScore'] == null ? undefined : json['riskScore'],
        'riskDetails': json['riskDetails'] == null ? undefined : json['riskDetails'],
    };
}

export function SupplyDetailsToJSON(json: any): SupplyDetails {
    return SupplyDetailsToJSONTyped(json, false);
}

export function SupplyDetailsToJSONTyped(value?: SupplyDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'package': FoodPackageOutToJSON(value['_package']),
        'habitat': HabitatNamesToJSON(value['habitat']),
        'image': EnclosureNamesToJSON(value['image']),
        'licenses': ((value['licenses'] as Array<any>).map(PermitOutToJSON)),
        'tags': ((value['tags'] as Array<any>).map(SupplyCategoryOutToJSON)),
        'vulnerabilities': ((value['vulnerabilities'] as Array<any>).map(VulnerabilityOutToJSON)),
        'dependsOn': ((value['dependsOn'] as Array<any>).map(SupplyOutToJSON)),
        'isOutdated': value['isOutdated'],
        'hasAllowedVersion': value['hasAllowedVersion'],
        'id': value['id'],
        'purl': value['purl'],
        'version': value['version'],
        'bomRef': value['bomRef'],
        'type': value['type'],
        'author': value['author'],
        'riskScore': value['riskScore'],
        'riskDetails': value['riskDetails'],
    };
}

