/* tslint:disable */
/* eslint-disable */
/**
 * Space Zoo Management API
 * API for managing the Galactic Space Zoo - home to exotic alien creatures from across the universe
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SupplyFilter
 */
export interface SupplyFilter {
    /**
     * 
     * @type {string}
     * @memberof SupplyFilter
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SupplyFilter
     */
    purl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SupplyFilter
     */
    _package?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SupplyFilter
     */
    version?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SupplyFilter
     */
    image?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SupplyFilter
     */
    bomRef?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SupplyFilter
     */
    type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SupplyFilter
     */
    author?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SupplyFilter
     */
    riskScore?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SupplyFilter
     */
    riskDetails?: string | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof SupplyFilter
     */
    licenses?: Array<number> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof SupplyFilter
     */
    dependsOn?: Array<number> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof SupplyFilter
     */
    tags?: Array<number> | null;
}

/**
 * Check if a given object implements the SupplyFilter interface.
 */
export function instanceOfSupplyFilter(value: object): value is SupplyFilter {
    return true;
}

export function SupplyFilterFromJSON(json: any): SupplyFilter {
    return SupplyFilterFromJSONTyped(json, false);
}

export function SupplyFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): SupplyFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'purl': json['purl'] == null ? undefined : json['purl'],
        '_package': json['package'] == null ? undefined : json['package'],
        'version': json['version'] == null ? undefined : json['version'],
        'image': json['image'] == null ? undefined : json['image'],
        'bomRef': json['bomRef'] == null ? undefined : json['bomRef'],
        'type': json['type'] == null ? undefined : json['type'],
        'author': json['author'] == null ? undefined : json['author'],
        'riskScore': json['riskScore'] == null ? undefined : json['riskScore'],
        'riskDetails': json['riskDetails'] == null ? undefined : json['riskDetails'],
        'licenses': json['licenses'] == null ? undefined : json['licenses'],
        'dependsOn': json['depends_on'] == null ? undefined : json['depends_on'],
        'tags': json['tags'] == null ? undefined : json['tags'],
    };
}

export function SupplyFilterToJSON(json: any): SupplyFilter {
    return SupplyFilterToJSONTyped(json, false);
}

export function SupplyFilterToJSONTyped(value?: SupplyFilter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'purl': value['purl'],
        'package': value['_package'],
        'version': value['version'],
        'image': value['image'],
        'bomRef': value['bomRef'],
        'type': value['type'],
        'author': value['author'],
        'riskScore': value['riskScore'],
        'riskDetails': value['riskDetails'],
        'licenses': value['licenses'],
        'depends_on': value['dependsOn'],
        'tags': value['tags'],
    };
}

