/* tslint:disable */
/* eslint-disable */
/**
 * Space Zoo Management API
 * API for managing the Galactic Space Zoo - home to exotic alien creatures from across the universe
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by openapi-ts-client.
 * https://github.com/fa-krug/openapi-ts-client
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TestCoverage } from './TestCoverage';
import {
    TestCoverageFromJSON,
    TestCoverageFromJSONTyped,
    TestCoverageToJSON,
    TestCoverageToJSONTyped,
} from './TestCoverage';
import type { CodeDuplication } from './CodeDuplication';
import {
    CodeDuplicationFromJSON,
    CodeDuplicationFromJSONTyped,
    CodeDuplicationToJSON,
    CodeDuplicationToJSONTyped,
} from './CodeDuplication';
import type { ReliabilityRating } from './ReliabilityRating';
import {
    ReliabilityRatingFromJSON,
    ReliabilityRatingFromJSONTyped,
    ReliabilityRatingToJSON,
    ReliabilityRatingToJSONTyped,
} from './ReliabilityRating';
import type { SecurityRating } from './SecurityRating';
import {
    SecurityRatingFromJSON,
    SecurityRatingFromJSONTyped,
    SecurityRatingToJSON,
    SecurityRatingToJSONTyped,
} from './SecurityRating';
import type { SecurityReviewRating } from './SecurityReviewRating';
import {
    SecurityReviewRatingFromJSON,
    SecurityReviewRatingFromJSONTyped,
    SecurityReviewRatingToJSON,
    SecurityReviewRatingToJSONTyped,
} from './SecurityReviewRating';
import type { MaintainabilityRating } from './MaintainabilityRating';
import {
    MaintainabilityRatingFromJSON,
    MaintainabilityRatingFromJSONTyped,
    MaintainabilityRatingToJSON,
    MaintainabilityRatingToJSONTyped,
} from './MaintainabilityRating';

/**
 * 
 * @export
 * @interface WellnessMetricIn
 */
export interface WellnessMetricIn {
    /**
     * 
     * @type {number}
     * @memberof WellnessMetricIn
     */
    id?: number | null;
    /**
     * Unique ID of the metric
     * @type {string}
     * @memberof WellnessMetricIn
     */
    metricId?: string | null;
    /**
     * Timestamp when the metric was collected
     * @type {Date}
     * @memberof WellnessMetricIn
     */
    datetime?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof WellnessMetricIn
     */
    habitatId?: number | null;
    /**
     * lines of code
     * @type {number}
     * @memberof WellnessMetricIn
     */
    linesOfCode?: number | null;
    /**
     * Percentage of test coverage in main branch
     * @type {TestCoverage}
     * @memberof WellnessMetricIn
     */
    testCoverage?: TestCoverage | null;
    /**
     * Percentage of code duplications in main branch
     * @type {CodeDuplication}
     * @memberof WellnessMetricIn
     */
    codeDuplication?: CodeDuplication | null;
    /**
     * reliability_rating in main branch
     * @type {ReliabilityRating}
     * @memberof WellnessMetricIn
     */
    reliabilityRating?: ReliabilityRating | null;
    /**
     * security_rating in main branch
     * @type {SecurityRating}
     * @memberof WellnessMetricIn
     */
    securityRating?: SecurityRating | null;
    /**
     * security_review_rating in main branch
     * @type {SecurityReviewRating}
     * @memberof WellnessMetricIn
     */
    securityReviewRating?: SecurityReviewRating | null;
    /**
     * maintainability_rating in main branch
     * @type {MaintainabilityRating}
     * @memberof WellnessMetricIn
     */
    maintainabilityRating?: MaintainabilityRating | null;
}

/**
 * Check if a given object implements the WellnessMetricIn interface.
 */
export function instanceOfWellnessMetricIn(value: object): value is WellnessMetricIn {
    return true;
}

export function WellnessMetricInFromJSON(json: any): WellnessMetricIn {
    return WellnessMetricInFromJSONTyped(json, false);
}

export function WellnessMetricInFromJSONTyped(json: any, ignoreDiscriminator: boolean): WellnessMetricIn {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'metricId': json['metricId'] == null ? undefined : json['metricId'],
        'datetime': json['datetime'] == null ? undefined : (new Date(json['datetime'])),
        'habitatId': json['habitat_id'] == null ? undefined : json['habitat_id'],
        'linesOfCode': json['linesOfCode'] == null ? undefined : json['linesOfCode'],
        'testCoverage': json['testCoverage'] == null ? undefined : TestCoverageFromJSON(json['testCoverage']),
        'codeDuplication': json['codeDuplication'] == null ? undefined : CodeDuplicationFromJSON(json['codeDuplication']),
        'reliabilityRating': json['reliabilityRating'] == null ? undefined : ReliabilityRatingFromJSON(json['reliabilityRating']),
        'securityRating': json['securityRating'] == null ? undefined : SecurityRatingFromJSON(json['securityRating']),
        'securityReviewRating': json['securityReviewRating'] == null ? undefined : SecurityReviewRatingFromJSON(json['securityReviewRating']),
        'maintainabilityRating': json['maintainabilityRating'] == null ? undefined : MaintainabilityRatingFromJSON(json['maintainabilityRating']),
    };
}

export function WellnessMetricInToJSON(json: any): WellnessMetricIn {
    return WellnessMetricInToJSONTyped(json, false);
}

export function WellnessMetricInToJSONTyped(value?: WellnessMetricIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'metricId': value['metricId'],
        'datetime': value['datetime'] == null ? value['datetime'] : value['datetime'].toISOString(),
        'habitat_id': value['habitatId'],
        'linesOfCode': value['linesOfCode'],
        'testCoverage': TestCoverageToJSON(value['testCoverage']),
        'codeDuplication': CodeDuplicationToJSON(value['codeDuplication']),
        'reliabilityRating': ReliabilityRatingToJSON(value['reliabilityRating']),
        'securityRating': SecurityRatingToJSON(value['securityRating']),
        'securityReviewRating': SecurityReviewRatingToJSON(value['securityReviewRating']),
        'maintainabilityRating': MaintainabilityRatingToJSON(value['maintainabilityRating']),
    };
}

